'use strict';
/*
 冲刺-独立写作-待批改
 */
define(function(){
  return [
  '<div class="main mid">',
  	'<div id="leftDiv" class="left-part">',
  	    '<div class="h182">',
            '<p class="p3 gray">',
            '{{if data.from == "exercise"}}',
               '<a href="/html/chongci.html"><span>冲刺练习</span></a><span class="sign">></span><span><a id="go1" href="#">写作批改</a></span><span class="sign">></span><span><a id="go2" href="#" category="{{data.category}}">{{data.cText}}</a></span><span class="sign">></span><span>{{data.sequence_number}}</span>',
            '{{else}}',
              '<a href="/html/{{data.from}}.html">返回</a>',
            '{{/if}}',
            '</p>',
            '<hr class="mleft25 hr_w725">',
            '<div class="stepss mid">',
            '   <div class="cir_line">',
            '       <span class="cirs mleft25 bgblue">1</span><span class="line lineblue"></span><span class="cirs bgblue">2</span><span class="line lineblue"></span><span class="cirs bgblue">3</span><span class="line lineblue"></span><span class="cirs bgblue">4</span><span class="line"></span><span class="cirs">5</span>',
            '   </div>',
            '   <div class="steps">',
            '       <span class="fleft blue" style="margin-left:55px;">提交</span><span class="blue" style="margin-left:77px;">等待老师抢作业</span><span class="blue" style="margin-left:65px;">待选老师</span><span class="blue" style="margin-left:90px;">待批改</span><span style="margin-left:92px;">获取成绩</span>',
            '   </div>',
            '</div>',

            '<p class="left25 sentence font13 pr10">',
               '<span class="bold" style="padding-right:5px;" id="jijing_question_id" category="{{data.category}}" jqid="{{data.id}}" from="{{data.from}}">{{data.sequence_number}} </span>',
               '{{data.content}}',
            '</p>',
            '<p class="gram-p correct-p">',
               '<span><a id = "jijingSample" href="#" class="see">答题范例</a></span><span>',
            '</p>',
            '<div id="jijingSampleDiv" class="ans" style="display:none;">',
               '<div class="arrow-up"></div>',
               '<div id="sampleContent" class="gram-p1 see-sample">',
                 'this is sample area',
               '</div>',
            '</div>',
        '</div>',
        '<div class="h202 user-content" >',
        '    <div>',
      '       <div class="mtop15 ">',
      '            <div class="fleft teacher-img teacher_info" teacherid="{{data.teacher_id}}">',
      '                  <img src="{{data.teacher_avatar}}" style="width:100%;border-radius: 35px;">',
      '             </div>',
      '             <div class="fleft mleft10">',
      '                  <span style="display: block;padding-top:5px;letter-spacing: 1px;">老师：<span>{{data.teacher_nickname}}</span></span><span class="grey76 " style="">您于<span>{{data.create_at}}</span>确认了<span>{{data.teacher_nickname}}</span>老师，请等待批改。</span>',
      '             </div>',
      '                   <div style="clear:both;"></div>',
      '             </div>',
      '          <p style="margin: 15px 0 0 25px;">我的作文',
      '              <span style="float:right;margin-right:30px;color:#5499ff;text-decoration:none;">{{if data.spend_time}}<img src="../../i/time.png"/><span>写作时长：</span><span id="writeTimer" style="margin-right:10px;">{{data.spend_time}}</span>{{/if}}共：<span>{{data.wordCount}}</span>词</span>',
      '          </p>',
        '        <div>',
        '            <hr class="mleft25 hr_w725">',
      '              <p class="p4 gray font12" style="padding-right: 30px;margin-bottom:0px;">',
      '                 <span id="spanTime" style="float:left;">{{data.answer_created_at}}</span>',
      //'                 <span class="pg_red " style="float:right;margin-left: 10px;">你的作业已经发送给<span>{{data.teacher_nickname}}</span>老师，请等待Ta的批改</span>',
      //'                 <span class="pg_red " style="float:right;">{{data.answer_created_at}}提交</span>',
      '              </p>',
        '            <p class="left25 jijingccwrite-p ">',
        '                <span id="spanAnswer" style="display: block;word-break:break-word;">{{#data.answerContent}}</span>',
        '            </p>',
        '            <div id="waitCheck" style="display:none;" class="left25 bgray round rewrite-percent detail-results">',
        '                <span class="number zonghe-bgray">待批</span>',
        '            </div>',
        '        </div>',
        '    </div>',
        '</div>',

    '</div>',

    '<div class="right-part3">',
        '<div class="rightsidebar h290">',
            '<p class="jinjing-speak-p" ><span id="groupTitle" class="bold" data="{{data.title}}">{{data.title}}</span></p>',
            '<div class="h200" id="rightitems">',
                '{{each data.questions as value index}}',
                '<hr class="jijing-hr">',
                '<p class="mleft25 h40 border-bto"><span class="num bold">{{value.sequence_number}}.</span>',
                '<a id="{{value.id}}" content="{{value.content}}" href="#" type="{{value.type}}" category="{{value.category}}" score="{{value.score}}" class="rightItem" answer_id="{{value.answer_id}}" sequence_number="{{value.sequence_number}}">',
                '{{value.content.substring(0,45)}}...',
                '</a>',
                '</p>',
                '{{/each}}',
            '</div>',
        '</div>',
    '</div>',
'</div>'
  ].join('');
});