'use strict';

define(function(){
  return [
    '<div class="main mid">',
        '<div id="leftDiv" class="left-part">',
            '<div class="h182">',
                '<p class="p3 gray">',
                    '{{if data.from == "exercise"}}',
                    '<a href="/html/chongci.html"><span>冲刺练习</span></a><span class="sign">></span><span><a id="go1" href="#">写作批改</a></span><span class="sign">></span><span><a id="go2" href="#" category="{{data.category}}">{{data.cText}}</a></span><span class="sign">></span><span>{{data.sequence_number}}</span>',
                    '{{else}}',
                    '<a href="/html/{{data.from}}.html">返回</a>',
                    '{{/if}}',
                '</p>',
                '<hr class="mleft25 hr_w725">',
                '<p class="left25 sentence" style="width: 730px;" id="sentence" content="{{data.content}}">',
                    '<span class="bold" style="padding-right:5px;" id="jijing_question_id" category="{{data.category}}" jqid="{{data.id}}" from="{{data.from}}">{{data.sequence_number}} </span>',
                    '{{data.content}}',
                '</p>',
                '<p class="gram-p correct-p">',
                    '<span><a id = "jijingSample" href="#" class="see">答题范例</a></span><span>',
                '</p>',
                '<div id="jijingSampleDiv" class="ans" style="display:none;">',
                    '<div class="arrow-up"></div>',
                    '<div id="sampleContent" class="gram-p1 see-sample">',
                        'this is sample area',
                    '</div>',
                '</div>',
            '</div>',
            '<div class="one-button2">',
                '<button type="button" class="btn btn-primary btn2" id="doAgain">再练一次</button>',
            '</div>',
            '<div id="showDetail" class="h202 user-content">',
            '    <div>',
            '        <p class="p1 bold font14 left25 gray">我的练习记录</p>',
            '        <div>',
            /*           type：0:未做,1:已保存, 2:待抢, 3:待选老师,4:待批改, 5:已批改*/
            '            {{each data.answer_messages as value index}}',
            '               <hr class="mleft25 hr_w725">',
            '               <p class="mleft25 gray font12"><span class="correct-ans">{{value.answer_created_at}}</span></p>',
            '               <div class="left25 jijingwrite-p" style="width:95%;">',
            '                   <span class="myanswer user-answer"  qtype="{{value.type}}" answer_id="{{value.answer_id}}" score="{{value.score}}">{{#value.cutAnswer}}</span>',
            '                   {{if value.type == "1"}}',
            '                       <div class="left25 rewrite-percent" style="top:5px;right:10px;"><span class="number pg_red">已保存</span></div>',
            '                   {{else if value.type == "2"}}',
            '                       <span class="number pg_red r_status mright10">等待老师抢作业</span>',
            '                   {{else if value.type == "3"}}',
            '                       <div class="" style="float: right;display: inline-block;margin-top: -15px;margin-right: 10px;">',
            '                           <div class="rewrite-fsingle "><span class="number pg_red">已有{{value.grap_amount}}位老师抢作业</span></div>',
            '                           <div ><button type="button" class="myanswer btn btn1 btn-primary" qid="{{data.id}}" answer_id="{{value.answer_id}}" qtype="{{value.type}}">选择老师</button></div>',
            '                       </div>',
            '                   {{else if value.type == "4"}}',
            '                      <div class="left25 rewrite-percent " style="top:5px;right:10px;"><span class="number pg_red">待批改</span></div>',
            '                   {{else if value.type == "5"}}',
            '                      <div class="left25 b-blue round rewrite-pri" style="top:5px;right:10px;"><span class="number">{{value.score}}分</span></div>',
            '                   {{/if}}',
            '               </div>',
            '            {{/each}}',
            '        </div>',
            '    </div>',
            '</div>',

'</div>',

'<div class="right-part3">',
'<div class="rightsidebar h290">',
  '<p class="jinjing-speak-p" ><span id="groupTitle" class="bold" data="{{data.title}}">{{data.title}}</span></p>',
  '<div class="h200" id="rightitems">',
  '{{each data.questions as value index}}',
  '<hr class="jijing-hr">',
  '<p class="mleft25 h40 border-bto"><span class="num bold">{{value.sequence_number}}.</span>',
  '<a id="{{value.id}}" content="{{value.content}}" href="#" type="{{value.type}}" category="{{value.category}}" score="{{value.score}}" class="rightItem" answer_id="{{value.answer_id}}" sequence_number="{{value.sequence_number}}">',
  '{{value.content.substring(0,45)}}...',
  '</a>',
  '</p>',
  '{{/each}}',
'</div>',
'</div>',
'</div>',
'</div>'
  ].join('')
});