'use strict'

define(function(){
    return [
        '<div class="h182">',
            '<p class="p3 gray">',
                '<span><a class="bold bread-gray speakjjUnit pointer" data-target="all">全部练习</a><span class="sign1 bread-gray">&gt;</span></span>',
                '<span><a class="bold bread-gray speakjjUnit pointer" data-target="parentMenu">口语批改</a></span><span class="sign1 bread-gray">&gt;</span>',
                '<span><a class="bold bread-gray speakjjUnit pointer speakjj-forcecast-gray" data-target="correction">综合口语批改</a></span><span class="sign1 bread-gray">&gt;</span>',
                '<span><a class="bold tpo-passage">{{data.question.question_sequence_number}}</a></span>',
                '<script type="text/javascript">$("#groupTitle").html("{{data.group_title}}")</script>',
            '</p>',
            '<hr class="mleft25 hr_w725"  />',
            '<p class="left25 sentence pr10" id="sentence">',
            '<span class="bold" style="padding-right:5px;" id="jijing_question_id" category="wjj" jqid="1627" from="exercise">{{data.question.question_sequence_number}}</span>',
            '{{data.question.content}}',
            '<audio src="{{data.question.audio_url}}" controls="controls" style="width:720px;height:50px;" id="audioAudio">亲 您的浏览器不支持html5的audio标签</audio>',
            '{{if data.question.material}}',
            '<p class="gram-p correct-p"><span><a id="jijingSampleTag" href="#" class="see font-blue ">阅读</a></span></p>',
                '<div id="jijingSampleDiv" class="ans" style="display: block;">',
                '<p class="left25 sentence" id="" content="" style="width:93%;">{{data.question.material}}</p>',
                '</div>',
            '{{/if}}',
            '{{if data.question.analysis}}',
                '<div class="mleft10">',
                '<ul class="nav nav-tabs nav-write-tabs" role="tablist" id="myTab">',
              /*  '<li role="presentation" class="bold">',
                '<a class="tabItem" href="#" data-target="Integralgain" id="IntegralgainTab" role="tab" data-toggle="tab">答案范例</a>',
                '</li>',*/
                '<li role="presentation" class=" active">',
                '<a class="tabItem" href="#" data-target="Integraluse" id="IntegraluseTab" role="tab" data-toggle="tab">讲解视频</a>',
                '</li>',
                '</ul>',
                '<div id="tab_record" class="tab-content tpo-write-tab" >',
                '<span id="flashcontent"></span>',
                '<!-- 中部选项卡1-录音控件 -->',
                '<div role="tabpanel" class="tab-pane " id="Integralgain">',
                '<div class="left25 height90">',

                '</div>',
                '</div>',
                '<!-- 选项卡2-视频播放 -->',
                '<div role="tabpanel" class="tab-pane active" id="Integraluse">',
                '{{if data.question.analysis}}',
                    '<div class="tpo-fun-round jijing-fun-round-video pointer audioPlay" data-source="{{data.question.analysis}}"><span class="tpo-span-style1" data-source="{{data.question.analysis}}">视频01</span></div>',
                '{{/if}}',
                '</div>',
                '</div>',
                '</div>',
            '{{/if}}',
        '</div>',


       '<div class="one-button2">',
          '<button type="button" class="btn btn-primary btn2" id="speakjj_doAgain">再来一遍</button>',
       '</div>',
       '<div class="h202">',
          '<div>',
             '<p class="p1 bold font14 left25 gray">我的练习记录</p>',
             '<div>',
                '{{each data.question.answers as value index}}',
                    '<hr class="mleft25 hr_w725" style="clear:both;margin:15px 0px 15px 25px;" />',
                   '<p class="p4 gray font12"><span class="correct-ans">{{value.answer_created_at.substring(0, 19).replace("T", "&nbsp;&nbsp;")}}</span></p>',
                   '<div class="">',
                      '<span class="font-right">{{value.answer_audio_length+"\'"}}</span>',
                      '<img  style="max-width: 52px; max-height: 52px;width:52px;height:52px;border-radius:26px; position: relative;" src="{{data.userHeadPic}}">',
                      '<img class="soundPlay" data-audioUrl="{{value.answer_content}}" src="../../i/dic-pic.png"  style="cursor: pointer;">',
                    '{{if value.type==1}}',
                    '<div class="left25  round rewrite-percent topnone " ><span data-answer_type="{{value.type}}" data-answer_id="{{value.answer_id}}" class="number speakjj-correction-done pg_red"  style="cursor: pointer">已保存</span></div>',
                    '{{else if value.type==2}}',
                    '<div class="rewrite-fsingle mright30" ><span data-answer_type="{{value.type}}" data-answer_id="{{value.answer_id}}" class="number pg_red speakjj-correction-done" style="cursor: pointer">等待老师抢作业</span></div>',
                    '{{else if value.type==3}}',
                    '<div class="mright30" style="float: right;display: inline-block;margin-top: -15px;text-align: right;"><div class="rewrite-fsingle " ><span class="number pg_red">已有{{value.grap_amount}}位老师抢作业</span></div><div class="" ><button data-answer_type="{{value.type}}" data-answer_id="{{value.answer_id}}" type="button" class="btn btn1 btn-primary speakjj-correction-done"  >选择老师</button></div></div>',
                    '{{else if value.type==4}}',
                    '<div class="rewrite-fsingle mright30 " ><span data-answer_type="{{value.type}}" data-teacher_id="{{value.teacherId}}" data-answer_id="{{value.answer_id}}" class="number pg_red speakjj-correction-done" style="cursor: pointer">待批改</span></div>',
                    '{{else if value.type==5}}',
                    '<div class="left25 b-blue round rewrite-pri" ><span data-answer_type="{{value.type}}" data-answer_id="{{value.answer_id}}" class="number speakjj-correction-done" style="cursor: pointer">{{value.score}}分</span></div>',
                    '{{/if}}',
                   '</div>',
                  /*  '{{if value.mark_audio_url}}',
                    '<div class="rewrite-percent1" style="margin-top:20px;margin-right:-5px;" >',
                        '<span class="font-right">{{value.mark_audio_length+"\'"}}</span>',
                        '<img class="soundPlay soundPlayRight" data-audioUrl="{{value.mark_audio_url}}" src="../../i/dic-pic3.png"  style="cursor: pointer;">',
                        '<img style="max-width: 52px; max-height: 52px;width:52px;height:52px;border-radius:26px; position: relative;"  src="{{value.teacher_avatar}}">',
                    '</div>',
                    '{{/if}}',*/
                '{{/each}}',
             '</div>',
          '</div>',
       '</div>'
    ].join('')
})
