'use strict';
/*
 冲刺-独立写作-已保存
 */
define(function(){
  return [
  '<div class="main mid">',
      '<div id="leftDiv" class="left-part">',
            '<div class="content h182">',
                '<p class="p3 gray">',
                '{{if data.from == "exercise"}}',
                    '<a href="/html/chongci.html"><span>冲刺练习</span></a><span class="sign">></span><span><a id="go1" href="#">写作批改</a></span><span class="sign">></span><span><a id="go2" href="#" category="{{data.category}}">{{data.cText}}</a></span><span class="sign">></span><span>{{data.sequence_number}}</span>',
                '{{else}}',
                    '<a href="/html/{{data.from}}.html">返回</a>',
                '{{/if}}',
                '</p>',
                '<hr class="mleft25 hr_w725">',
                '            <div class="stepss mid">',
                '               <div class="cir_line">',
                '                   <span class="cirs mleft25 bgblue">1</span><span class="line "></span><span class="cirs ">2</span><span class="line"></span><span class="cirs">3</span><span class="line"></span><span class="cirs">4</span><span class="line"></span><span class="cirs">5</span>',
                '               </div>',
                '               <div class="steps">',
                '                   <span class="fleft blue" style="margin-left:55px;">提交</span><span class="" style="margin-left:77px;">等待老师抢作业</span><span style="margin-left:65px;">待选老师</span><span style="margin-left:90px;">待批改</span><span style="margin-left:92px;">获取成绩</span>',
                '               </div>',
                '            </div>',
                '<p class="left25 sentence font13 pr10">',
                    '<span class="bold" style="padding-right:5px;" id="jijing_question_id" answer_id="{{data.answer_id}}" category="{{data.category}}" jqid="{{data.id}}" from="{{data.from}}">{{data.sequence_number}} </span>',
                    '{{data.content}}',
                '</p>',
                //'<p class="gram-p correct-p">',
                //    '<span><a id = "jijingSample" href="#" class="see">答题范例</a></span><span>',
                //'</p>',
                '<div id="jijingSampleDiv" class="ans" style="display:none;">',
                    '<div class="arrow-up"></div>',
                    '<div id="sampleContent" class="gram-p1 see-sample">',
                    'this is sample area',
                    '</div>',
                '</div>',
            '</div>',

            '<div class="h202 user-content" >',
            '    <div>',
      '              <p style="margin: 18px 0 0 27px;">已保存' +
      '                  <span style="float:right;margin-right:30px;color:#5499ff;text-decoration:none;">{{if data.spend_time}}<img src="../../i/time.png"/><span>写作时长：</span><span id="writeTimer" style="margin-right:10px;">{{data.spend_time}}</span>{{/if}}共：<span>{{data.wordCount}}</span>词</span>',
      '              </p>',
            '        <div>',
            '            <hr class="mleft25 hr_w725">',
            '            <p class="p4 gray font12"><span style="padding-right: 20px;font-weight: bold;">我的作文</span><span id="spanTime" class="correct-ans">{{data.answer_created_at}}</span></p>',
            '            <p class="left25 jijingccwrite-p ">',
            '                <span id="spanAnswer" style="display: block;word-break:break-all;">{{#data.answerContent}}</span>',
            '            </p>',
            '            <div id="hasSave" style="display:none;" class="left25 b-lred round rewrite-percent detail-results">',
            '                <span class="number">已保存</span>',
            '            </div>',
            '        </div>',
            '        <div class="one-button2">',
            '             <button id="notCorrection_submit" question_id="{{data.id}}" data_type="{{data.type}}" category="{{data.category}}" type="button" class="btn1 btn btn-primary" >批改</button>',
            '             <input id="articleAnswer" type="hidden" value="{{data.answerContent_original}}"/><input id="question_id" type="hidden" value="{{data.id}}"/>',
            '        </div>',
            '    </div>',
            '</div>',
//  '<div class="h202">',
//   '<div class="">',
//      '<p class="p1 bold center">请等待老师批改</p>',
//      '<hr class="mleft25">',
//      '<p class="p4 bold"><span class="correct-ans">我的作文:</span><div class="left25 bred round rewrite-percent" style="top:0;"><span class="number ">已保存</span></div></p>',
//      '<p class="left25 sentence score-p6 right13" style="word-wrap:break-word;">{{#data.answerContent}}</p>',
//      '<div class="one-button3"  style="text-align:center;">',
//      '<button id="notCorrection_submit" question_id="{{data.id}}" data_type="{{data.type}}" category="{{data.category}}" type="button" class="btn1 btn btn-primary" >批改</button>',
//      '<input id="articleAnswer" type="hidden" value="{{data.answerContent_original}}"/><input id="question_id" type="hidden" value="{{data.id}}"/>',
//      '</div>',
//  '</div>',
//'</div>',
'</div>',

'<div class="right-part3">',
'<div class="rightsidebar h290">',
  '<p class="jinjing-speak-p" ><span id="groupTitle" class="bold" data="{{data.title}}">{{data.title}}</span></p>',
  '<div class="h200" id="rightitems">',
  '{{each data.questions as value index}}',
  '<hr class="jijing-hr">',
  '<p class="mleft25 h40 border-bto"><span class="num bold">{{value.sequence_number}}.</span>',
  '<a id="{{value.id}}" content="{{value.content}}" href="#" type="{{value.type}}" category="{{value.category}}" score="{{value.score}}" class="rightItem" answer_id="{{value.answer_id}}" sequence_number="{{value.sequence_number}}">',
  '{{value.content.substring(0,45)}}...',
  '</a>',
  '</p>',
  '{{/each}}',
'</div>',
'</div>',
'</div>',
'</div>',
'<!--信息提示框-->',
'<div class="modal fade" id="write_errorTip" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">',
'<div class="modal-dialog">',
'<div class="modal-content" style="width:354px;border: 1px solid #C2BFBF;border-top: 7px solid #509bfd;;">',

'<div class="modal-body" style="height:90px;line-height:90px;">',
'<p id="write_errorMsg" class="feedback-title" style="text-align:center;">您的积分不足，无法提交？</p>',
'</div>',
'<div style="margin: 0px auto 20px auto;text-align: center;">',
'<button type="button" class="btn btn-primary btn-sm feedback-button2 btn1" id="write_errorTip_sure">确认</button>',
'</div>',
'</div>',
'</div>',
'</div>',
'    <div class="modal fade in" id="waitPayModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;">',
'        <div class="modal-dialog" >',
'            <div class="modal-content" style="width:354px;border: 1px solid #C2BFBF;border-top: 7px solid #509bfd;">',
'                <div class="modal-body">',
'                    <p id="txtShow" class="feedback-title1" style="padding-left:0;text-align: center;"></p>',
'                </div>',
'                <div style="text-align:center;margin: 10px auto 20px auto;">',
'                    <button type="button" data-dismiss="modal" class="btn btn-default btn-sm feedback-button5" data-dismiss="modal" id="cancleSave">取消</button>',
'                    <button type="button" data-dismiss="modal" class="btn btn-primary btn-sm  btn1" id="gotoPay">确认</button>',
'                </div>',
'            </div>',
'        </div>',
'    </div>',
'<div class="modal fade in" id="payModel" tabindex="-1" role="dialog" style="display: none;">',
'    <div class="modal-dialog" >',
'       <div class="modal-content"  style="width:354px;border: 1px solid #C2BFBF;border-top: 7px solid #509bfd;text-align:center;">',
'           <div class="modal-body">',
'               <p class="topaymodel" >已完成支付？</p>',
'           </div>',
'           <div style="text-align:center;margin:10px auto 20px auto;">',
'           <button type="button" data-dismiss="modal" class="btn btn-warning btn-sm " id="payFail1">支付遇到问题</button>',
'           <button type="button" data-dismiss="modal" class="btn btn-primary btn-sm  btn1" id="paySuccess1">支付成功</button>',
'           </div>',
'       </div>',
'    </div>',
'</div>'
  ].join('')
});