'use strict'

define(function(){
    return [
        '<div class="right-part2">',
        '<ul class="tabWrite tabs_new forecast_tabs" role="tablist" id="myTab">',
        '{{each data.tabs as tab index}}',
        '<li role="presentation" tabstatus="allWork" class="allWork {{if (index==0 && !data.activeTab) || data.activeTab==tab.group_id}}current{{/if}}" >',
        '<a href="#" role="tab" data-toggle="tab"  style="width:140px;" data-groupsid="{{tab.group_id}}" class="forecastTab" >{{tab.group_title}}</a>',
        '</li>',
        '{{/each}}',
        '</ul>',
        '<div class="right_part_jjyc">',
        '<div role="tabpanel" class="tab-pane active" id="wslContent">',
       // '<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" style="margin-left:-10px;margin-right:10px;"><span>{{data.group_title}}</span></p>',
        '<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" style="margin-left:-10px;margin-right:10px;"><span>{{data.group_title}}</span></p>',
        '<hr class="mleft25" />',
        '{{each data.questions as value index}}',
            '<div class="jjyc_box jijing-speak-div-js">',
            '<div class="jjyc_table">',
            '<div style=" vertical-align:middle;display:table-cell;width:680px;">',
            //'<p class="left25 mleft20 font13 jj-speak-padding jj-speak-list-js">',  '</p>',
            '{{if value.category==1}}',
            '<span class="jjyc_bluebg"><span class="font14 jjyc_bgfont">大范围</span></span>',
            '{{else if value.category==2}}',
            '<span class="jjyc_bluebg"><span class="font14 jjyc_bgfont">小范围</span></span>',
            '{{/if}}',
        //'<p class=" font13 jj-speak-padding jj-speak-list-js">',
        //    '<span class="num bold ">{{value.question_sequence_number}}</span>',
        //    '<a href="#"  data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.question_content.length>180?value.question_content.substr(0,180)+"..." : value.question_content}}</a>',
        //    '<span class="fright pg_red">已保存</span>',
        //'</p>',

            '{{if value.type==1}}',
                '<p class=" font13  jj-speak-list-js">',
                '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
                '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.question_content.length>180?value.question_content.substr(0,180)+"..." : value.question_content}}</a>',
                '<span class="fright pg_red">已保存</span>',
                '</p>',
            '{{else if value.type==2}}',
                '<p class=" font13  jj-speak-list-js">',
                '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
                '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.question_content.length>180?value.question_content.substr(0,180)+"..." : value.question_content}}</a>',
                '<span class="fright pg_red">等待老师抢作业</span>',
                '</p>',
            '{{else if value.type==3}}',
                '<p class=" font13  jj-speak-list-js">',
                '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
                '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class="sim-width480" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.question_content.length>180?value.question_content.substr(0,180)+"..." : value.question_content}}</a>',
                '<span class="fright pg_red">已有{{value.grap_amount}}位老师抢作业</span>',
                '</p>',
            '{{else if value.type==4}}',
                '<p class=" font13  jj-speak-list-js">',
                '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
                '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.question_content.length>180?value.question_content.substr(0,180)+"..." : value.question_content}}</a>',
                '<span class="fright pg_red">待批改</span>',
                '</p>',
            '{{else if value.type==5}}',
                '<p class=" font13  jj-speak-list-js">',
                '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
                '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.question_content.length>180?value.question_content.substr(0,180)+"..." : value.question_content}}</a>',
                '<span class="left25 b-blue round rewrite-percentnew " ><span class="number">{{value.score}}分</span></span>',
                '</p>',
            '{{else}}',
                '<p class=" font13  jj-speak-list-js">',
                '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
                '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class="sim-a2" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.question_content.length>180?value.question_content.substr(0,180)+"..." : value.question_content}}</a>',
                '</p>',
            '{{/if}}',
        '</div>',
        '</div>',
        '</div>',

        '{{/each}}',
        '</div></div>',
        '</div>'
    ].join('')
})
