'use strict'

define(function(){
    return [
        '<div class="h182">',
            '<p class="p3 gray">',
                '<span><a class="bold bread-gray speakjjUnit pointer" data-target="all">全部练习</a><span class="sign1 bread-gray">&gt;</span></span>',
                '<span><a class="bold bread-gray speakjjUnit pointer" data-target="parentMenu">口语批改</a></span><span class="sign1 bread-gray">&gt;</span>',
                '<span><a class="bold bread-gray speakjjUnit pointer speakjj-forcecast-gray" data-target="correction">综合口语批改</a></span><span class="sign1 bread-gray">&gt;</span>',
                '<span><a class="bold tpo-passage">{{data.question.question_sequence_number}}</a></span>',
                '<script type="text/javascript">$("#groupTitle").html("{{data.group_title}}")</script>',
            '</p>',
            '<hr class="mleft25 hr_w725" />',
                '<div class="stepss mid">',
                    '<div class="cir_line  ">',
                    '<span class="cirs mleft25 bgblue">1</span><span class="line lineblue"></span><span class="cirs bgblue">2</span><span class="line lineblue"></span><span class="cirs bgblue">3</span><span class="line lineblue"></span><span class="cirs bgblue">4</span><span class="line lineblue"></span><span class="cirs bgblue">5</span>',
                    '</div>',
                    '<div class="steps">',
                    '<span class="fleft blue" style="margin-left:55px;">提交</span><span class="blue" style="margin-left:77px;">等待老师抢作业</span><span  class="blue" style="margin-left:65px;">待选老师</span><span class="blue" style="margin-left:90px;">待批改</span><span class="blue" style="margin-left:92px;">获取成绩</span>',
                    '</div>',
                '</div>',
            '<p class="left25 sentence pr10" id="sentence">',
            '<span class="bold" style="padding-right:5px;" id="jijing_question_id" category="wjj" jqid="1627" from="exercise">{{data.question.question_sequence_number}}</span>',
            '{{data.question.content}}',
            '<audio src="{{data.question.audio_url}}" controls="controls" style="width:720px;height:50px;" id="audioAudio">亲 您的浏览器不支持html5的audio标签</audio>',
            '{{if data.question.material}}',
            '<p class="gram-p correct-p"><span><a id="jijingSampleTag" href="#" class="see font-blue ">阅读</a></span></p>',
                '<div id="jijingSampleDiv" class="ans" style="display: block;">',
                '<p class="left25 sentence" id="" content="" style="width:93%;">{{data.question.material}}</p>',
                '</div>',
            '{{/if}}',
            '{{if data.question.analysis}}',
            '<div class="mleft10">',
            '<ul class="nav nav-tabs nav-write-tabs" role="tablist" id="myTab">',
            /*  '<li role="presentation" class="bold">',
             '<a class="tabItem" href="#" data-target="Integralgain" id="IntegralgainTab" role="tab" data-toggle="tab">答案范例</a>',
             '</li>',*/
            '<li role="presentation" class=" active">',
            '<a class="tabItem" href="#" data-target="Integraluse" id="IntegraluseTab" role="tab" data-toggle="tab">讲解视频</a>',
            '</li>',
            '</ul>',
            '<div id="tab_record" class="tab-content tpo-write-tab" >',
            '<span id="flashcontent"></span>',
            '<!-- 中部选项卡1-录音控件 -->',
            '<div role="tabpanel" class="tab-pane " id="Integralgain">',
            '<div class="left25 height90">',

            '</div>',
            '</div>',
            '<!-- 选项卡2-视频播放 -->',
            '<div role="tabpanel" class="tab-pane active" id="Integraluse">',
            '{{if data.question.analysis}}',
            '<div class="tpo-fun-round jijing-fun-round-video pointer audioPlay" data-source="{{data.question.analysis}}"><span class="tpo-span-style1" data-source="{{data.question.analysis}}">视频01</span></div>',
            '{{/if}}',
            '</div>',
            '</div>',
            '</div>',
            '{{/if}}',
        '</div>',

        '<div class="h202" style="overflow:visible;">',
        '<p class="p3 gray">',
        '<span><a class="bold black jinJieUnit pointer">综合口语批改详情</a></span>',
        '</p>',
        '<hr class="mleft25 hr_w725" />',
        //'<span>',
        //'<span class="user-img mleft35 teacher_info" style="overflow: hidden" teacherId="{{data.answerDetail.teacher_id}}"><img src="{{data.answerDetail.teacherInfo.avatar}}" style="width:100%; border-radius:35px;" ></span>',
        //'<span class="mleft35">{{data.answerDetail.teacherInfo.nickName}}</span>',
        //'</span>',
        //'<div class="left25 b-blue round rewrite-percent" style="right:20px;margin-top:-45px;">',
        //'<span class="number">{{data.answerDetail.score}}分</span>',
        //'</div>',
        '           <table class="inf_list mleft25" style="border:none;">',
        '             <tr>',
        '               <th style="border:none;" class="img_linew teacher_info " teacherid="{{data.answerDetail.teacherInfo.teacherId}}"><img  class="img_liimg" src="{{data.answerDetail.teacherInfo.avatar || \'http://newbbs.b0.upaiyun.com/avater/avater.png\'}}" ><p class="font14 black mtop5" style="margin-bottom:0px;">{{data.answerDetail.teacherInfo.nickName}}</p></th>',
        '               <th class="">',
        '                   <div class="date_t" style="height:22px;line-height:21px;">',
        '                       <span class="mright20" style="float:left;">批改数量：<span>{{data.answerDetail.teacherInfo.correctTotal}}</span></span>',
        '                       <span>',
        '                          <span class="black3" style="float:left;">综合评价：</span>',
        '                          <span class="" style="float:left;">',
        '                             <span class="commstar_pg commstar1" style="line-height: 22px;"><span class="commstar_pg commstar2 {{data.parseClass(data.answerDetail.teacherInfo.scoreFinal)}}"></span></span>',
        '                          </span>',
        '                       </span>',
        '                   </div>',
        '                   <div class="date_ts">',
        '                       <span class="mright20">{{data.teacherType==1 ?"口语老师":"写作老师"}}</span>手机号：<span >{{data.answerDetail.teacherInfo.phone}}</span>',
        '                   </div>',
        '                   <div class="font_lidiv" style="width:482px;"><span class="width25">{{data.answerDetail.teacherInfo.comment}}</span></div>',
        '               </th>',
        '               <th style="text-align: right;">',
        '                   <span style="font-weight: normal;" class="gray font12">{{data.formatDate(data.answerDetail.createTime,\'yyyy-MM-dd hh:mm:ss\')}}</span>' ,
        '                   <div class="left25 b-blue round  mtop10" style="">',
        '                       <span class="number">{{data.answerDetail.score}}分</span>',
        '                   </div>',
        '                   <button type="button" class="P_btn mtop10"   isPingJia="{{data.answerDetail.isFeedback}}" answerId="{{data.answerDetail.answer_id}}" teacherId="{{data.answerDetail.teacherInfo.teacherId}}">{{data.answerDetail.isFeedback==0?"评价老师":"查看评价"}}</button>',
        '               </th>',
        '             </tr>',
        '           </table>',

       // '<span style="float:right;margin-right:20px; font-size:13px;">{{data.formatDate(data.answerDetail.createTime,\'yyyy-MM-dd hh:mm:ss\')}}</span>',
        '{{if data.answerDetail.answer_new_content}}',
        '<hr class="mleft25 hr_w725" />',
        '<p class="gram-p correct-p font13 black"><span>老师已经把您的录音转化成了文本,批改已经在文本上标注了，请点击查看文本</span></p>',
        '<div id="speak_jijingSampleDiv" class="ans" style="display: block;">',
        '<p class="left25 sentence" id="" content="" style="width:93%;word-wrap:break-word;">{{#data.answerDetail.answer_new_content || data.answerDetail.answer_content}}</p>',
        '</div>',
        '{{/if}}',
        '</div>',

        '{{if data.answerDetail.is_old==true}}',
            '<div class="h202">',
                '<div role="tabpanel" class="tab-pane" id="Integralgain">',
                    '<div class="repeat-record top30">',
                        '<p id="recordTimerP"><span id="recordTimer" >00:00</span>/<span id="recordTotalLength">00:00</span></p>',
                        '<audio src="{{data.answerDetail.mark_tips[0].audio_url}}"  id="teacherCorrectionAudio">亲 您的浏览器不支持html5的audio标签</audio>',
                        '<!--播放录音--><img id="playTeacherCorrectionAudio" data-audioUrl="{{data.answerDetail.mark_tips[0].audio_url}}" style="display:inline;" src="../../i/repeat-pic4.png" class="repeat-pic10 pointer">',
                        '<!--播放中--><img id="playingTeacherCorrectionAudio" src="../../i/repeat-pic3.png" class="repeat-pic10"  style="display:none;"></div>',
                    '</div>',
                '</div>',
            '</div>',
        '{{else}}',
            '<div id="teacherCorrectionAudioDiv" class="h202" style="display: none;">',
                '<div role="tabpanel" class="tab-pane"  id="Integralgain">',
                    '<div class="repeat-record top30">',
                        '<p id="recordTimerP"><span id="recordTimer" >00:00</span>/<span id="recordTotalLength">00:00</span></p>',
                        '<audio src=""  id="teacherCorrectionAudio">亲 您的浏览器不支持html5的audio标签</audio>',
                        '<!--播放录音--><img id="playTeacherCorrectionAudio" data-audioUrl="" style="display:inline;" src="../../i/repeat-pic4.png" class="repeat-pic10 pointer">',
                        '<!--播放中--><img id="playingTeacherCorrectionAudio" src="../../i/repeat-pic3.png" class="repeat-pic10"  style="display:none;"></div>',
                    '</div>',
                '</div>',
            '</div>',
        '{{/if}}'
    ].join('')
})
