'use strict'

define(function(){
    return [
        '<div class="right-part1">',
        '<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" style="margin-left:-10px;margin-right:10px;"><span>{{data.group_title}}</span></p>',
        '<hr class="mleft25 hr_w725" />',
        '{{each data.questions as value index}}',
        /*'<p class="left25 font13 jijing-speak-div">',
           // '<img src="../../i/icon-top1.png " class="zonghe-img">',
            '<span class="num bold">{{value.question_sequence_number}}</span>',
            '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class="sim-a2" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.content}}</a>{{if value.is_today_task}}<span class="orange left16">今日任务</span>{{/if}}',
            '{{if value.type==1}}',
            '<div class="left25 bred round rewrite-percent zonghe-one" ><span class="number">已保存</span></div>',
            '{{else if value.type==2}}',
            '<div class="left25 bgray round rewrite-percent zonghe-one" ><span class="number zonghe-bgray">待抢</span></div>',
            '{{else if value.type==3}}',
            '<div class="left25 bgray round rewrite-percent zonghe-one" ><span class="number zonghe-bgray">已有多少位老师抢作业</span></div>',
            '{{else if value.type==4}}',
            '<div class="left25 bgray round rewrite-percent zonghe-one" ><span class="number zonghe-bgray">待批改</span></div>',
            '{{else if value.type==5}}',
            '<div class="left25 b-blue round rewrite-percent zonghe-one" ><span class="number">{{value.score}}分</span></div>',
            '{{/if}}',
        '</p>',*/
        '{{if value.type==1}}',
        '<p class="left25 mleft20 font13 jj-speak-padding jj-speak-list-js">',
        '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
        '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.content.length>180?value.content.substr(0,180)+"..." : value.content}}</a>',
        '<span class="fright pg_red">已保存</span>',
        '</p>',
        '{{else if value.type==2}}',
        '<p class="left25 mleft20 font13 jj-speak-padding jj-speak-list-js">',
        '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
        '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.content.length>180?value.content.substr(0,180)+"..." : value.content}}</a>',
        '<span class="fright pg_red">等待老师抢作业</span>',
        '</p>',
        '{{else if value.type==3}}',
        '<p class="left25 mleft20 font13 jj-speak-padding jj-speak-list-js">',
        '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
        '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.content.length>180?value.content.substr(0,180)+"..." : value.content}}</a>',
        '<span class="fright pg_red">已有{{value.grap_amount}}位老师抢作业</span>',
        '</p>',
        '{{else if value.type==4}}',
        '<p class="left25 mleft20 font13 jj-speak-padding jj-speak-list-js">',
        '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
        '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.content.length>180?value.content.substr(0,180)+"..." : value.content}}</a>',
        '<span class="fright pg_red">待批改</span>',
        '</p>',
        '{{else if value.type==5}}',
        '<p class="left25 mleft20 font13  jj-speak-padding jj-speak-list-js">',
        '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
        '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class=" sim-width510" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.content.length>180?value.content.substr(0,180)+"..." : value.content}}</a>',
        '<span class="left25 b-blue round rewrite-percentnew " ><span class="number">{{value.score}}分</span></span>',
        '</p>',
        '{{else}}',
        '<p class="left25 mleft20 font13 jj-speak-padding jj-speak-list-js">',
        '<span class="num bold sin_num">{{value.question_sequence_number}}</span>',
        '<a href="#" data-question_id="{{value.question_id}}" data-type="1" category="wjj" score="0" class="sim-a2" answer_id="" sequence_number="{{value.question_sequence_number}}">{{value.content.length>180?value.content.substr(0,180)+"..." : value.content}}</a>',
        '</p>',
        '{{/if}}',
        '{{/each}}',
        '</div>'
    ].join('')
})
