'use strict'

define(function(){
    return [
        /*蛟哥注释掉的部分是另一种情况，再练一次*/
        '<div class="h182">',
        '<p class="p3 gray">',
        '<span><a class="bold bread-gray speakjjUnit pointer" data-target="all">全部练习</a><span class="sign1 bread-gray">&gt;</span></span>',
        '<span><a class="bold bread-gray speakjjUnit pointer" data-target="parentMenu">口语批改</a></span><span class="sign1 bread-gray">&gt;</span>',
        '{{if !data.paperExamsYearObj}}',
        '<span><a class="bold bread-gray speakjjUnit pointer speakjj-forcecast-gray" data-target="jjForecast">独立口语</a></span><span class="sign1 bread-gray">&gt;</span>',
        '<span><a class="bold tpo-passage">{{data.group_title}} {{data.question.question_sequence_number}}</a></span>',
        '{{else}}',
        '<span><a class="bold bread-gray speakjjUnit pointer speakjj-paperExams-gray" data-target="jjPaperExams" data-group_id="{{data.paperExamsYearObj.group_id}}">历年真题</a></span><span class="sign1 bread-gray">&gt;</span>',
        '<span><a class="bold tpo-passage">{{data.paperExamsYearObj.group_title}} {{data.question.question_sequence_number}}</a></span>',
        '{{/if}}',
        '<script type="text/javascript">$("#groupTitle").html("{{data.group_title}}")</script>',
        '</p>',
        '<hr class="mleft25 hr_w725" />',

        '<p class="left25 sentence  pr10" id="sentence" content="Do you agree or disagree with the following statement: Professional athletes who receive high salaries, such as football or basketball players, deserve what they have got.">',
        '<span class="bold" style="padding-right:5px;" id="jijing_question_id" category="wjj" jqid="1627" from="exercise">{{data.question.question_sequence_number}}</span>',
        '{{data.question.question_content}}',
        '<div class="mleft10">',
            '<ul class="nav nav-tabs nav-write-tabs" role="tablist" id="myTab">',
            '<li role="presentation" class="active bold">',
            '<a class="tabItem" href="#" data-target="Integralgain" id="IntegralgainTab" role="tab" data-toggle="tab">答案范例</a>',
            '</li>',
            '<li role="presentation" class=" bold">',
            '<a class="tabItem" href="#" data-target="Integraluse" id="IntegraluseTab" role="tab" data-toggle="tab">讲解视频</a>',
            '</li>',
            '</ul>',
            '<div id="tab_record" class="tab-content tpo-write-tab" >',
                '<span id="flashcontent"></span>',
                '<!-- 中部选项卡1-录音控件 -->',
                '<div role="tabpanel" class="tab-pane active" id="Integralgain">',
                    '<div class="left25 height90">',
                        '{{if data.question.sample_messages}}',
                        '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{data.question.sample_messages.teacher_avatar }}">',
                        '<p>{{data.question.sample_messages.teacher_nickname}}</p>',
                        '<img data-audioUrl="{{data.question.sample_messages.sample_content}}" src="../../i/dic-pic.png" class="jijing-speak-dic soundPlay" id="" style="cursor: pointer;">',
                        '{{/if}}',
                    '</div>',
                '</div>',
                '<!-- 选项卡2-视频播放 -->',
                '<div role="tabpanel" class="tab-pane" id="Integraluse">',
                    '{{if data.question.question_analysis}}',
                    '<div class="tpo-fun-round jijing-fun-round-video pointer audioPlay" data-source="{{data.question.question_analysis}}"><span class="tpo-span-style1" data-source="{{data.question.question_analysis}}">视频01</span></div>',
                    '{{/if}}',
                '</div>',
            '</div>',
        '</div>',
        '</div>',
        '</div>',


        '<div class="one-button2">',
        '<button type="button" class="btn btn-primary btn2" id="speakjj_doAgain">再练一次</button>',
        '</div>',
        '<div class="h202">',
        '<div>',
        '<p class="p1 bold font14 left25 gray">我的练习记录</p>',
        '<div>',
            '{{each data.question.answers as value index}}',
                '<hr class="mleft25 hr_w725" style="clear:both;margin:15px 0px 15px 25px;" />',
                '<p class="pleft27 gray font12"><span class="correct-ans">{{value.answer_created_at.substring(0, 19).replace("T", "&nbsp;&nbsp;")}}</span></p>',
                '<div class="left25">',

                '<div style="display:inline-block;">',
                '<img class="img_liimg"  src="{{data.userHeadPic}}">',
                '</div>',
                '<div style="display:inline-block;position: absolute;">',
                '<span class="font-right left45">{{value.answer_audio_length+"\'"}}</span>',
                '<img class="soundPlay" data-audioUrl="{{value.answer_audio_url}}" src="../../i/dic-pic.png"  style="cursor: pointer;">',
                '</div>',

                '{{if value.type==1}}',
                '<div class="left25  round rewrite-percent topnone " ><span data-answer_type="{{value.type}}" data-answer_id="{{value.answer_id}}" class="number pg_red speakjj-correction-done" style="cursor: pointer">已保存</span></div>',
                '{{else if value.type==2}}',
                '<div class="rewrite-fsingle mright30" ><span data-answer_type="{{value.type}}" data-answer_id="{{value.answer_id}}" class="number pg_red speakjj-correction-done" style="cursor: pointer">等待老师抢作业</span></div>',
                '{{else if value.type==3}}',
                '<div class="mright30" style="float: right;display: inline-block;margin-top: -30px;text-align: right;"><div class="rewrite-fsingle " ><span class="number pg_red">已有{{value.grap_amount}}位老师抢作业</span></div><div class="" ><button data-answer_type="{{value.type}}" data-answer_id="{{value.answer_id}}" type="button" class="btn btn1 btn-primary speakjj-correction-done"  >选择老师</button></div></div>',
                '{{else if value.type==4}}',
                '<div class="rewrite-fsingle mright30 " ><span data-answer_type="{{value.type}}" data-teacher_id="{{value.teacherId}}" data-answer_id="{{value.answer_id}}" class="number pg_red speakjj-correction-done" style="cursor: pointer">待批改</span></div>',
                '{{else if value.type==5}}',
                '<div class="left25 b-blue round rewrite-pri" ><span data-answer_type="{{value.type}}" data-answer_id="{{value.answer_id}}" class="number speakjj-correction-done" style="cursor: pointer">{{value.score}}分</span></div>',
                '{{/if}}',
                '</div>',
            '{{/each}}',
        '</div>',
        '</div>',
        '</div>'
    ].join('')
})
