'use strict'

define(function(){
  return [
 '<div class="sidebar">',
   '<div class="list-group" id="firstpane">',
   '<ul class="sidebar-ul ">',
   '<li>',
       '<a id="side1" href="##" class="list-group-item side-border1 bold menu_head lida"><img src="../../i/side-pic16.png" class="side-pic">写作批改<img src="../../i/side-ang1.png" style="margin-left: 85px;" id="writeImg"></a>',
         '<div id="wirte_menu_div" style="display:none;">',
         '<ul>',
           '<li class="lida2 side-li ">',
            '<a id="side2" href="##"  class="list-group-item side-border1 bold  subsidebar lida3 height45"><img src="../../i/side-pic21.png" class="side-pic">独立写作</a>',
           '</li>',
           '<li class="lida2 side-li ">',
             '<a id="side3" href="##"  class="list-group-item side-border1 bold subsidebar lida3 height45"><img src="../../i/side-pic22.png" class="side-pic">历年真题</a>',
           '</li>',
            '<li class="lida2 side-li ">',
              '<a id="side9" href="##"  class="list-group-item side-border1 bold subsidebar lida3 height45"><img src="../../i/side-pic28.png" class="side-pic">综合写作批改</a>',
            '</li>',
         '</ul>',
         '</div>',
   '</li>',
   '<li>',
       '<a id="side4" href="##" class="list-group-item side-border2 bold menu_head lida height45"><img src="../../i/side-pic9.png" class="side-pic">口语批改<img src="../../i/side-ang1.png" style="margin-left: 85px;" id="speakImg"></a>',
         '<div id="speak_menu_div" style="display:none;">',
         '<ul>',
           '<li class="lida2 side-li ">',
            '<a id="side5" href="##"  class="list-group-item side-border2 bold  subsidebar lida3 height45"><img src="../../i/side-pic21.png" class="side-pic">独立口语</a>',
           '</li>',
           '<li class="lida2 side-li ">',
             '<a id="side6" href="##"  class="list-group-item side-border2 bold subsidebar lida3 height45"><img src="../../i/side-pic22.png" class="side-pic">历年真题</a>',
           '</li>',
           '<li class="lida2 side-li ">',
              '<a id="side8" href="##"  class="list-group-item side-border2 bold subsidebar lida3 height45"><img src="../../i/side-pic28.png" class="side-pic">综合口语批改</a>',
           '</li>',
         '</ul>',
         '</div>',
   '</li>',
    '<li>',
      '<a href="#" id="side7" class="list-group-item side-border1 bold menu_head current lida height45"><img src="../../i/shua-tpo2.png" class="side-pic">TPO阅读刷题</a>',
    '</li>',
    '<li>',
      '<a href="#" id="side10" class="list-group-item side-border2 bold menu_head current lida height45"><img src="../../i/shua-tpo1.png" class="side-pic">TPO听力刷题</a>',
    '</li>',
   '</ul>',
   '</div>', 
  '</div>',
  ].join('')
})
