'use strict';

define(function () {
    return [
        '<div class="sidebar">',
        '<div class="list-group">',
        '<div id="sidePerson">',
        '   <div class="head-div">',
        '       <img src="http://newbbs.b0.upaiyun.com/avater/avater.png" id="personImgSide" class="i8 border35"  width="120" height="120">',
        '       <p class="p7" id="sideNickname"></p>',
        '   </div>',
        '</div>',
        '<div class="list-group" id="firstpane">',
        '<ul class="sidebar-ul ">',
        // '{{if data}}',
        // '<ul class="sidebar-ul bwrite" >',
        //   '{{each data as value index}}',
        //   '<li>',
        //     '<a href="##" id="{{value.id}}" class="bold menu_head current lida ">{{value.content}}</a>',
        //     '<hr class="hr6 mleft25 person-hr">',
        //     '</li>',
        //   '{{/each}}',
        // '{{/if}}',
        '<li>',
        '   <a href="mycourse.html" class="list-group-item side-border2 bold menu_head current lida side height45"><img src="../i/any-sideimg1.png" class="side-pic"/>我的课程</a>',
        '</li>',
        '<li>',
        '   <a href="mycoupon.html" class="list-group-item side-border1 bold menu_head current lida side height45"><img src="../i/any-sideimg2.png" class="side-pic"/>我的优惠</a>',
        '</li>',
        '<li>',
        '   <a id="mywallet" href="mywallet.html" class="list-group-item side-border2 bold menu_head current lida side height45"><img src="../i/side-pic32.png" class="side-pic"/>我的钱包</a>',
        '</li>',
        '<li>',
        '   <a href="baofenplan.html" class="list-group-item side-border2 bold menu_head current lida side height45"><img src="../i/any-sideimg3.png" class="side-pic"/>保分计划</a>',
        '</li>',
        '<li>',
        '   <a href="##" id="side1" class="list-group-item side-border1 bold menu_head current lida side height45" style="margin-bottom:-2px;"><img src="../i/side-pic20.png" class="side-pic"/>个人主页</a>',
        '</li>',
        '<li>',
        '   <a id="side2" href="xiezuopigai.html" class="list-group-item side-border2 bold menu_head lida"><img src="../i/side-pic18.png" class="side-pic">批改成绩<img src="../i/side-ang1.png" style="margin-left: 85px;" id="pigaiImg"/></a>',
        '   <div id="pigai_menu_div" style="display:none;">',
        '      <ul>',
        '      <li class="lida2 side-li sidebarLight"><a id="side4" href="xiezuopigai.html" class="list-group-item  side-border2 bold subsidebar lida3 "><img src="../i/side-pic26.png" class="side-pic">写作批改</a></li>',
        '      <li class="lida2 side-li"><a id="side5" href="speakscore.html" class="list-group-item  side-border2 bold subsidebar lida3"><img src="../i/side-pic27.png" class="side-pic"/>口语批改</a></li>',
        '      </ul>',
        '   </div>',
        '</li>',
        '<li style="display:none;">',
        '   <a href="##" id="side6" class="list-group-item side-border1 bold menu_head current lida side height45"><img src="../i/side-pic23.png" class="side-pic">积分</a>',
        '</li>',
        '<li>',
        '   <a href="##" id="side3" class="list-group-item side-border1 bold menu_head current lida side height45"><img src="../i/side-pic19.png" class="side-pic">我的消息</a>',
        '</li>',
        '<ul>',
        '</div>',
        '</div>',
        '</div>'
    ].join('')
});
