'use strict'

define(function(){
  return [
    '<div class="right-part1"> ',
  '<div class="content h650">',
    '<div class="rewr-div">',
     //'<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" class="list-pic">记忆复写</p>',
     '<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" class="list-pic">{{data.xm_title}}</p>',
   '</div>',
    '<hr class="mleft25">',
    '<div class="mid in-block-style">',
    '<div class="in-block">',
     '<div class="b-blue round1 rewrite-style">',
      '<span class="number1">1</span>',
     '</div>',
     '<div class="line1 rebordergreen"></div>',
     '<span class="rewrite-check">查看范文</span>',
    '</div>',
    '<div class="in-block">',
     '<div class="b-blue round1 rewrite-style1">',
      '<span class="number1">2</span>',
     '</div>',
     '<div class="line2 rebordergreen "></div>',
      '<span class="rewrite-read">开始复写</span>',
    '</div>',
    '<div class="in-block">',
     '<div class="b-blue round1 rewrite-style1 rewrite-style3-round">',
      '<span class="number1">3</span>',
     '</div>',
     '<span class="rewrite-write">查看成绩</span>',
    '</div>',
   /*  '<div class="in-block">',
     '<div class="bgray round1 rewrite-style2">',
      '<span class="number1">4</span>',
     '</div>',
      '<span class="rewrite-score">成绩</span>',
     '</div>',*/
     '</div>',
    /*'<hr class="mleft25">',*/
    '<div class="left25 top40 font13">',
      '<p>',
        '<span class="" style="float:left;"><a href="##">英文</a></span>',
        '<span class="left25" style="padding-bottom: 10px;"><a href="##">按段复写/</a><a href="##">整篇复写</a></span>',
      '</p>',
      '<p>',
        '<span class="grey" style="padding-bottom: 10px;">文章认为广告包括那些为招揽业务，产品或服务，或者是为了促进公司或个人的公关片。</span>',
        '<textarea spellcheck="false" autocomplete="off" class=" form-control bordergreen rewrite-tarea" rows="5" placeholder=""></textarea>',
      '</p>',
      '<div class="one-button3">',
      '<button id="btnSubmit" type="button" class="btn1 btn btn-primary active" >提交</button>',
    '</div>',
    '</div>',
  '</div>',
 '</div>'
  ].join('')
})