'use strict';

define(function(){
  return [
   '<div class="right-part1">',
  '<div class="content h650">',
    '<p class="p1 bold mleft25 black"><img src="../../i/list-pic.png" class="list-pic">记忆复写</p>',
    '<hr class="mleft25">',
    '{{if data.reproduction_questions}}',
    '{{each data.reproduction_questions as value index}}',
      '{{if value.isLock}}',
        '<p class="default-cursor left25 font13 rewrite-repeat" style="position: relative">',
        '<span class="num bold">{{value.sequence_number}}.</span>',
        '<a class="sim-a1" href="javascript:;">{{value.content}}',
        '<span class="disContent" style="display:none">{{value.allContent}}</span>',
        '<span class="disContentCH" style="display:none">{{value.content_ch}}</span>',
        '</a>',
        //'{{if value.is_today_task}}',
        //  '<span class="orange left16" style="position: absolute;bottom: 10px;left: 0px;">今日任务</span>',
        //'{{/if}}',
        '<span class="team-score1 green" style="margin-left:20px;font-size:12px;position:absolute;right:20px;bottom:10px;">',
        '<img src="{{value.imgflagUrl}}" alt="" class=" tp0">',
        '</span>',
      '{{else}}',
        '<p class="showDetail left25 font13 rewrite-repeat"  style="position: relative" data-id={{value.id}} data-num={{value.sequence_number}} top_score="{{value.top_score}}" group_level="{{value.group_level}}" avg_speed="{{value.avg_speed}}">',
        '<span class="num bold">{{value.sequence_number}}.</span>',
        '<a class="sim-a1" href="javascript:;">{{value.content}}',
        '<span class="disContent" style="display:none">{{value.allContent}}</span>',
        '<span class="disContentCH" style="display:none">{{value.content_ch}}</span>',
        '</a>',
        //'{{if value.is_today_task}}',
        //'<span class="orange left16" style="position: absolute;bottom: 10px;left: 0px;">今日任务</span>',
        //'{{/if}}',
        '<span class="team-score1 green" style="margin-left:20px;font-size:12px;position:absolute;right:20px;bottom:10px;">',
          '{{if !value.biggestUnlockNoDone}}',
          '<img src="{{value.imgflagUrl}}" alt="" class=" tp0">',
          '{{/if}}',
        '</span>',
        '</p>',
      '{{/if}}',
    '{{/each}}',
    "{{/if}}",
    '{{if data.flag}}',
      '<p class="center">登录之后，查看更多</p>',
      '<div class="one-button">',
      '<button type="button" class="btn btn1 btn-primary active" id="rewriteLogin">登录</button>',  
    '</div>',
    '{{/if}}',
  '</div>',

  '</div>',
  /**未解锁提示**/
    '<div class="modal fade" id="lockModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">',
    '<div class="modal-dialog">',
    '<div class="modal-content" style="width:354px;border: 1px solid #C2BFBF;border-top: 7px solid #509bfd;">',
    '<div class="modal-body">',
    '<p id="lockTip" class="feedback-title" style="text-align:center;top:0px;">前一单元90%正确,24分钟每题才能解锁此单元</p>',
    '</div>',
    '<div class="one-button3" style="text-align:center;">',
    '<button type="button" class="btn btn-primary btn-sm feedback-button2 btn1" id="lockSure" onclick="javaScript:$(\'#lockModal\').modal(\'hide\')">确定</button>',
    '</div>',
    '</div>',
    '</div>',
    '</div>'
  ].join('')
})
