'use strict'

define(function(){
  return [
'<div class="right-part1"> ',
'<div class="content h650">',
    '<div class="rewr-div">',
        '<p class="p1 bold mleft25 black"><img src="../../i/list-pic.png" class="list-pic">{{data.xm_title}}',
          '<span class="time-pos1">',
          '<img src="../../i/time.png">',
          '<a href="#" style="color:#00b551">计时</a>',
          '<a class="mytime" style="color:#00b551" href="#">：</a><a id="testTimer4" class="mytime" style="color:#00b551" href="#">00:00:00</a>',
          '</span>',
        '</p>',
    '</div>',
    '<hr class="mleft25">',
    '<div class="mid in-block-style">',
        '<div class="in-block">',
            '<div class="b-blue round1 rewrite-style">',
            '<span class="number1">1</span>',
            '</div>',
            '<div class="line1 rebordergreen"></div>',
            '<span class="rewrite-check">查看范文</span>',
        '</div>',
        '<div class="in-block">',
            '<div class="b-blue round1 rewrite-style1">',
            '<span class="number1">2</span>',
            '</div>',
            '<div class="line2 rebordergray "></div>',
            '<span class="rewrite-read">开始复写</span>',
        '</div>',
        '<div class="in-block">',
            '<div class="bgray round1 rewrite-style1 rewrite-style3-round">',
            '<span class="number1">3</span>',
            '</div>',
            '<span class="rewrite-write">查看成绩</span>',
        '</div>',
    '</div>',
    '<p class="left25 top40 font13">',
       /* '<span class="num bold">{{data.index + 1}}.</span>{{data.subject}}',*/
      '{{data.subject}}',
    '</p>',
    '<div class="left25 top40 font13">',
      '<p>',
        '<span class="" style="float:left;"><a href="##" id="btnen" data="cn">英文<span class="green">（*查看将不判断成绩）</span></a></span>',
        '<span class="left25" style="padding-bottom: 10px;">',
        /*'<a id="duan" href="##" class="bold rewrite-green">按段复写/</a>',
        '<a id="pian" href="##">整篇复写</a></span>',*/
      '</p>',
      //'<p>',
        '<!--段的中文解释-->',
        '<p id="piancn" class="grey" style="padding-bottom: 10px;display:block">{{data.cn}}</p>',
        '<!--整篇的中文解释-->',
        '<span id="piancn1" class="grey" style="padding-bottom: 10px;display:none">',
        '{{each data.cnAll as value index}}',
          '<p class="piancn" class="grey" style="padding-bottom: 10px;">{{value}}</p>',
        '{{/each}}',
        '</span>',
        '<!--段的英文-->',
        '<span id="duanAns" class="grey" style="padding-bottom: 10px;display:none" onselectstart="return false">',
        '{{data.en}}',
        '</span>',
        '<!--整篇的英文-->',
        '<span id="pianAns" class="grey" style="padding-bottom: 10px;display:none" onselectstart="return false">',
        '{{each data.enAll as value index}}',
          '<p class="piancn" class="grey" style="padding-bottom: 10px;">{{value}}</p>',
        '{{/each}}',
        '</span>',
        '<textarea id="userContent" spellcheck="false" autocomplete="off" class="form-control rewrite-tarea" style="background-color:rgb(246, 246, 246);" rows="7" placeholder="" onpaste="return false" ></textarea>',
      //'</p>',
   '</div>',


     '<div class="one-button" style="margin-top:40px;">',
      '<button id="btnSubmit" type="button" class="btn1 btn btn-primary active" >提交</button>',
    '</div>',
  '</div>',
  '</div>',
 '</div>'
  ].join('')
})