'use strict'

define(function(){
  return [
  '<div class="right-part1">',
   '<div class="h53">',
    '<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" style="margin-left:   -6px;margin-right:10px;">练习历史</p>',
    '<hr class="mleft25">',
   '</div>',
   '<div class="content h450">',
    '<div class="training-hoistory">',
      '<ul>',
      '{{if data.hisVol.sequence_number=="" && data.hisGram.sequence_number=="" && data.hisDic.sequence_number==""}}',
        '<li>',
          '<span>暂无历史记录</span> ',
        '</li>',
      '{{/if}}',
      '{{if data.hisVol.sequence_number}}',
       '<li>',
        '<span class="orange" >[阅读词汇]</span>',
        '<span class="pointer lineHover hisGo history-space1" data-type="1" data-group_level="{{data.hisVol.group_level}}" data-avg_speed="{{data.hisVol.avg_speed}}" data-unit="{{data.hisVol.sequence_number}}" data-groupId="{{data.hisVol.id}}">阅读词汇第{{data.hisVol.sequence_number}}单元</span>',
        '<span class="span2 history-time1">{{data.hisVol.created_at}}</span>',       
      '</li>',
      '{{/if}}',
      '{{if data.hisGram.sequence_number}}',
      '<li>',
        '<span class="orange">[语法]</span>',
        '<span class="pointer lineHover hisGo history-space1" data-type="2" data-group_level="{{data.hisGram.group_level}}" data-avg_speed="{{data.hisGram.avg_speed}}" data-groupId="{{data.hisGram.id}}">语法第{{data.hisGram.sequence_number}}单元</span>',
        '<span class="span2 history-time1">{{data.hisGram.created_at}}</span>',
      '</li>',
      '{{/if}}',
      '{{if data.hisDic.sequence_number}}',
      '<li>',
        '<span class="orange">[听写]</span>',
        '<span class="pointer lineHover hisGo history-space1" data-type="3" data-group_level="{{data.hisDic.group_level}}" data-avg_speed="{{data.hisDic.avg_speed}}" data-id="{{data.hisDic.id}}" data-unit="{{data.hisDic.sequence_number}}" data-unitId="{{data.hisDic.unit_id}}">听写第{{data.hisDic.sequence_number}}单元</span>',
        '<span class="span2 history-time1">{{data.hisDic.created_at}}</span>',
      '</li>',
      '{{/if}}',
      '{{if data.hisLis.sequence_number}}',
      '<li>',
        '<span class="orange">[音义互辨]</span>',
        '<span class="pointer lineHover hisGo history-space1" data-group_level="{{data.hisLis.group_level}}" data-avg_speed="{{data.hisLis.avg_speed}}" data-type="1{{data.hisLis.type}}" data-index="{{data.hisLis.index}}" data-sequence_number="{{data.hisLis.sequence_number}}" data-error_question_ids="{{data.hisLis.error_question_ids}}">音义互辨第{{data.hisLis.sequence_number}}单元</span>',
        '<span class="span2 history-time1">{{data.hisLis.created_at}}</span>',
      '</li>',
      '{{/if}}',
     '</ul>',
  '</div>',
 '</div>',
'</div>'
  ].join('')
})