'use strict'

define(function(){
  return [
    '<div class="right-part1">',
    '<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" style="margin-left:-6px;margin-right:10px;"><span>重点练习</span></p>',
    '<hr class="mleft25">',
        // '正确率{{data[0].rate}}',
        //     '平均速度{{data[0].avg_speed}}',
     '<ul>',
     '<li>',
      '{{each data as value index}}',
      '{{if value.typeName == "重点"}}',
      '<p class="totel-unit">',
      '<a href="#" groupid="{{value.id}}" data-locked="{{value.locked}}"  data-rate="{{value.rate}}" data-group_level="{{value.group_level}}" class="goGrammarUnit">',
      // 'unit{{value.sequence_number}} [{{value.typeName}}]',
      'unit{{value.sequence_number}}',
      '</a>{{if value.is_today_task}}<span class="orange left16">今日任务</span>{{/if}}',
      '{{if value.locked==0}}',
          /*'{{if value.rate !=null}} <a href="#" class="goResult" groupid="{{value.id}}">(正确率: {{value.ratePercent}})</a> {{/if}}',*/
          '{{if null != value.rate}}',
              '{{if value.group_level == 0}}',
                '<img src="../../i/newimg-0.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" data-rate="{{value.rate}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
              '{{if value.group_level == 1}}',
                '<img src="../../i/newimg-4.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" data-rate="{{value.rate}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
              '{{if value.group_level == 2}}',
                '<img src="../../i/newimg-1.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" data-rate="{{value.rate}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
              '{{if value.group_level == 3}}',
                '<img src="../../i/newimg-2.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" data-rate="{{value.rate}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
              '{{if value.group_level == 4}}',
                '<img src="../../i/newimg-3.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" data-rate="{{value.rate}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
          // '{{else}}',
          //     '<img src="../../i/i25-5.png" groupid="{{value.id}}" class="i25-6 goGrammarUnit pointer">',
          '{{/if}}',
      '{{else}}',
         '<img src="../../i/side-pic42.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" data-rate="{{value.rate}}" data-groups-id="{{value.id}}" data-volUnit="{{value.sequence_number}}" data-questionCount="{{value.question_count}}" data-rate="{{value.rate}}" data-errorQuestionIds="{{value.error_question_ids}}" class="i25-6">',
      '{{/if}}',
      '</p>',
      '{{/if}}',
      '{{/each}}',
      '</li>',
     '</ul>', 
    '<p class="p1 bold black mleft25" style="clear:both;padding-top: 25px;"><img src="../../i/list-pic.png" style="margin-left:-10px;margin-right:10px;"><span>难点练习</span></p>',
     '<hr class="mleft25">',
     '<ul>',
     '<li>',
      '{{each data as value index}}',
      '{{if value.typeName == "难点"}}',
      '<p class="totel-unit">',
      '<a href="#" data-locked="{{value.locked}}" data-group_level="{{value.group_level}}"  groupid="{{value.id}}" class="goGrammarUnit">',
      // 'unit{{value.sequence_number}} [{{value.typeName}}]',
      'unit{{value.sequence_number}}{{if value.is_today_task}}<span class="orange left16">今日任务</span>{{/if}}',
      '</a>',

      /*'{{if value.rate !=null}} <a href="#" class="goResult" groupid="{{value.id}}">(正确率: {{value.ratePercent}})</a> {{/if}}',*/
      // '{{if value.rate !=null}} <img src="../../i/i25-6.png" class="i25-6"></a> {{/if}}',
      '{{if value.locked==0}}',
          '{{if value.rate !=null}}',
              '{{if value.group_level == 0}}',
                '<img src="../../i/newimg-0.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
              '{{if value.group_level == 1}}',
                '<img src="../../i/newimg-4.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
              '{{if value.group_level == 2}}',
                '<img src="../../i/newimg-1.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
              '{{if value.group_level == 3}}',
                '<img src="../../i/newimg-2.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
              '{{if value.group_level == 4}}',
                '<img src="../../i/newimg-3.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" groupid="{{value.id}}" class="i25-6 goResult pointer">',
              '{{/if}}',
          // '{{else}}',
          //     '<img src="../../i/i25-5.png" groupid="{{value.id}}" class="i25-6 goGrammarUnit pointer">',
          '{{/if}}',
      '{{else}}',
         '<img src="../../i/side-pic42.png" data-group_level="{{value.group_level}}" data-avg_speed="{{value.avg_speed}}" data-rate="{{value.rate}}" data-groups-id="{{value.id}}" data-volUnit="{{value.sequence_number}}" data-questionCount="{{value.question_count}}" data-rate="{{value.rate}}" data-errorQuestionIds="{{value.error_question_ids}}" class="i25-6">',
      '{{/if}}',
      '</p>',
      '{{/if}}',
      '{{/each}}',
      '</li>',
     '</ul>',    
  '</div>',

      /**未解锁提示**/
      '<div class="modal fade" id="lockModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">',
          '<div class="modal-dialog">',
              '<div class="modal-content" style="width:354px;border: 1px solid #C2BFBF;border-top: 7px solid #509bfd;">',
                  '<div class="modal-body">',
                    '<p class="feedback-title" style="text-align:center;top:0px;">前一单元90%正确,2.5秒每词才能解锁此单元</p>',
                  '</div>',
                  '<div class="one-button3" style="text-align:center;">',
                    '<button type="button" class="btn btn-primary btn-sm feedback-button2 btn1" id="lockSure" onclick="javaScript:$(\'#lockModal\').modal(\'hide\')">确定</button>',
                  '</div>',
              '</div>',
          '</div>',
      '</div>',


  ].join('')
})