'use strict'

define(function(){
  return [
  '<div class="right-part1">',
   /* '<p class="p1 bold black message-space"><img src="../../i/list-pic.png" class="list-pic">正在练习第<span id="volUnit"></span>单元</p>',
    '<span class="unit"><a href="#" id="unitVol">选择单元</a></span>',*/
    '<p class="p1 bold black message-space"><img src="../../i/list-pic.png" class="list-pic">练习报告</p>',
    '<hr>',
    '{{if data.volErr.length}}',
    '{{if data.rate < 50}}',
       '<div class="practice-result">',
      '<img src="../../i/3.png" class="result-img">',
       // '<span class="result1 result-gray">正确率:{{data.rate}}%</span>',
       '<span class="result1 result-gray">对{{data.rate}}&nbsp;错{{100-data.rate}}</span>',
      '</div>',
      '<div class="practice-result">',
        '<span class="result2 result-gray">小盆友差的有点远哦~</span>',
      '</div>',
      '{{/if}}',
      '{{if data.rate >= 50 && data.rate <= 80 }}',
       '<div class="practice-result">',
      '<img src="../../i/1.png" class="result-img">',
       // '<span class="result1 result-orange">正确率:{{data.rate}}%</span>',
       '<span class="result1 result-gray">对{{data.rate}}&nbsp;错{{100-data.rate}}</span>',
      '</div>',
      '<div class="practice-result">',
        '<span class="result2 result-orange">娃 你已经超越了好多小伙伴。继续加油哦！</span>',
      '</div>',
      '{{/if}}',
      '{{if data.rate > 80 }}',
       '<div class="practice-result">',
      '<img src="../../i/2.png" class="result-img">',
        // '<span class="result1 result-red">正确率:{{data.rate}}%</span>',
        '<span class="result1 result-gray">对{{data.rate}}&nbsp;错{{100-data.rate}}</span>',
         '</div>',
      '<div class="practice-result">',
        '<span class="result2 result-red">学霸升级中~加油吧亲！</span>',
      '</div>',
      '{{/if}}',
      '<p style="padding-left:27px;">答错词汇：</p>',
      '{{each data.volErr as value index}}',
        '<div class="table W645">',
          '<ul>',
            '<li  class="vol-space3">',
              // '<span class="vol-space1">{{value.sequenceNumber}}.&nbsp;</span>',
              '<span class="td1 vol-space4">{{value.prompt}}</span>',
            '</li>',
            '<li class="vol-space5">',
              '<span class="vol-translation">{{value.explanation}}</span>',
             '</li>',
          '</ul>',
        '</div>',
      '{{/each}}',
       '<div class="two-button">',
       '<button type="button" class="btn btn-primary btn9" id="againVol">再来一遍</button>',
      '<button type="button" class="btn btn-primary btn2" id="errOnlyVol">重做错题</button>',
      '<button type="button" class="btn btn-primary btn1 {{if data.canUnLocked!=1}}disabled{{/if}}" id="nextUnitVol">下一单元</button>',
      // '<button type="button" class="btn btn-primary  " style="margin-left:20px;background:#509bfd!important" id="nextUnitVol">练习下一单元</button>',
      '</div>',
    '{{else if data.volErr.length == 0}}',
         '<div class="practice-result">',
      '<img src="../../i/2.png" class="result-img">',
        '<span class="result1 result-red">正确率:100%</span>',
         '</div>',
      '<div class="practice-result">',
        '<span class="result2 result-red">学霸升级中~加油吧亲！</span>',
      '</div>',
       '<div class="one-button">',
      '<button type="button" class="btn btn-primary btn9" id="againVol">再来一遍</button>',
      '<button type="button" class="btn btn-primary btn1 {{if data.canUnLocked!=1}}disabled{{/if}}" id="nextUnitVol">下一单元</button>',
      // '<button type="button" class="btn btn-primary active btn3 vol-space8" id="nextUnitVol">练习下一单元</button>',
      '</div>',
    '{{else}}',
    '{{/if}}',
  '</div>'
  ].join('')
})