'use strict';

define(function(){
  return [
    	'{{ if data}}',
   	 	'<div class="right-part1">',
    	'<p class="p1 bold black mleft25">',
        '<img src="../../i/list-pic.png" style="margin-left:-6px;margin-right:10px;">',
        //'<span>正在练习第<label>{{data.group_num}}</label>单元</span><span class="unit"><a id="selectUnit" href="#" group_id="{{data.group_id}}">选择单元</a></span>',
//      '<span>听写第<label>{{data.sequence_number}}</label>单元</span><span class="unit"><a id="selectUnit" href="#" group_id="{{data.group_id}}"></a></span>',//20160926
				'<span>{{data.title}}</span>',
        '<span class="time-pos">',
        '<img src="../../i/time.png">',
        '<a href="#" id="timeBtnStaus">计时</a>',
        '<a class="mytime" href="#">：</a><a id="testTimer2" class="mytime" href="#">00:00:00</a>',
        '</span>',
    	'</p>',
    	'<hr class="mleft25">',
    	'<p class=" margin30 mleft25 " id="seqNum">{{data.questionNum + "/" + data.questions.length}}</p>',
    	//'<img src="../../i/dic-pic.png" class="dic-pic" id="soundImg" style="cursor: pointer;">',
    	'<div style="margin:10px 0px 10px 25px;font-size:16px;" id="question-stem" >{{data.stem}}</div>',
    	'{{if data.audioUrl}}',
    	'<div class="audiojsZ newaudio " id="audiojs_wrapper0" style="width: 682px;">',
      '    <audio id="myMusic" src="{{data.audioUrl}}" preload="auto"></audio>',
      '    <div class="play-pauseZ"><p class="playZ"></p>',
      '        <p class="pauseZ"></p>',
      '        <p class="loadingZ"></p>',
      '        <p class="errorZ"></p>',
      '    </div>',
      '    <div class="newscrubberZ scrubberZ" style="width:496px!important;">',
      '        <div class="progressZ" style="width: 0px;"></div>',
      '        <div class="loadedZ" style="width: 375px;"></div>',
      '    </div>',
      '    <div class="timeZ"><em class="playedZ">00:00</em>| <strong class="durationZ">00:00</strong></div>',
      '    <div class="error-messageZ"></div>',
      '    <div class="change-voice" style="display:none;"></div>',
      '    <div class="sound setsound" style="margin-left:0;margin-right: 30px;cursor:pointer;display:none;">',
      '        <div class="play-voice" style="width:100%;"></div>',
      '        <div class="voice-bigger"></div>',
      '    </div>',
      '</div>',
      '{{/if}}',
    /*'<div class="bar">',
    '{{include "tmpl_jplayer"}}',
    '</div>',*/
    '<div id="answer" class="dic-pra" style="margin-top:50px;">',
     '<p class="dic-p"> ',
     '{{each data.lineNum as value index}}',
      '{{if value.type=="line_dict"}}',
          '<input tabindex="0" spellcheck="false" type="text" data-type="{{value.type}}" data-order="{{value.order}}" data-suborder="{{value.subOrder}}" class="left25 dic-input1 {{if value.subOrder>0}}linedict{{/if}}">',
          '{{else if value.type=="line"}}',
          '<label class="dic-line">—</label>',
          '{{else}}',
          '<input tabindex="0" spellcheck="false" type="text" class="left25 dic-input1">',
          '{{/if}}',
     '{{/each}}',
    '</p>',
    '</div>',
    '<p class="gram-p2" style="margin-left:-10px;">',
   /*'<span><a id="lookAnswer" href="#" class="see" style="color:#5499ff;">查看答案</a></span>',*/
    '<span style="padding-left:40px;"><a id="clearAnswer" href="#" class="see" style="color:#5499ff;">清除答案</a></span>',
    '</p>',
    '<div class="ans" style="display:none;">',
        '<div class="arrow-up">',
        '<!--向上的三角-->',
        '</div>',
        '<div class="mleft25 see-dicans">',
        '<p id="sureAnswer" class="dic-ans" onselectstart="return false">{{data.sample}}</p>',
        '</div>',
    '</div>',
    '<div class="one-button2">',
    '<button id="nextSub" type="button" class="btn1 btn btn-primary active" >下一题<button>',
    '</div>',
    '</div>',
    '{{ /if }}'
  ].join('')
})