'use strict'

define(function(){
  return [
  '<div class="right-part1">',
   '<div class="content h53">',
    '<p class="p1 bold all-blue mleft25">练习历史</p>',
    '<hr class="mleft25">',
   '</div>',
   '<div class="content h450">',
    '<div class="training-hoistory">',
      '<ul>',
      '{{if data.hisVol.sequence_number=="" && data.hisGram.sequence_number=="" && data.hisDic.sequence_number==""}}',
        '<li>',
          '<span>暂无历史记录</span> ',
        '</li>',
      '{{/if}}',
      '{{if data.hisVol.sequence_number}}',
       '<li>',
        '<span class="orange" >[词汇]</span>',
        '<span>阅读词汇第{{data.hisVol.sequence_number}}单元</span> ',
        // '<span class="span2" >{{data.hisVol.time}}</span>',
        '<span class="span2">2014-10-14  17：26</span>',  
        '</li>',
      '{{/if}}',
      '{{if data.hisGram.sequence_number}}',
      '<li>',
        '<span class="orange">[语法]</span>',
        '<span>语法第{{data.hisGram.sequence_number}}单元</span> ',
        // '<span class="span2">{{data.hisGram.time}}</span>',
        '<span class="span2">2014-10-14  17：26</span>',  
      '</li>',
      '{{/if}}',
      '{{if data.hisDic.sequence_number}}',
      '<li>',
        '<span class="orange">[听写]</span>',
        '<span>听写第{{data.hisDic.sequence_number}}单元</span> ',
        // '<span class="span2">{{data.hisDic.time}}</span>',
        '<span class="span2">2014-10-14  17：26</span>',  
      '</li>',
      '{{/if}}',
     '</ul>',
  '</div>',
 '</div>',
'</div>'
  ].join('')
})