'use strict'

define(function(){
  return [
    '<div class="right-part1">',
    '<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" style="margin-left: -6px;margin-right:10px;"><span>已练习498个听写</span></p>',
    '<hr class="mleft25">',
       '<p class="left margin30 mleft25 bold" id="seqNum">{{data["dictation_question"]["sequence_number"]}}</p>',
    '<img src="../../i/dic-pic.png" class="dic-pic" id="soundImg" style="cursor: pointer;">',
   /* '<div class="bar"></div>',
    '{{include "tmpl_jplayer"}}',*/
    '<div class="dic-pra">',
     '<p class="dic-p"> ',
      '<input type="text" class="left25 dic-input1">',
      '<span> ,</span> ',
      '<input type="text" class="dic-input2"> ',
    '</p>',
    '<p class="dic-p1">',
      '<input type="text" class="left25 dic-input3">',
      '<span> ,</span> ',
      '<input type="text" class="dic-input4">',
    '</p>',
    '<p class="dic-p1">',
      '<input type="text" class="left25 dic-input5">',
      '<span> ,</span> ',
      '<input type="text" class="dic-input6">',
    '</p>',
    '<p class="dic-p1"> ',
      '<input type="text" class="left25 dic-input1"> ',
      '<span> ,</span> ',
      '<input type="text" class="dic-input2"> ',
    '</p>',
    '<p class="dic-p1">',
      '<input type="text" class="left25 dic-input3"> ',
      '<span> ,</span> ',
      '<input type="text" class="dic-input4">',
    '</p> ',
    '</div>',
     '<p class="gram-p2"><span><a href="#" class="see">查看答案</a></span></p>',
     '<div class="ans" style="">',
      '<div class="arrow-up">',
      '</div>',
      '<div class="mleft25 see-dicans">',
        '<p class="dic-ans" style="width:600px;height:72px;line-height: 22px;text-align:left;padding-left:20px;padding-top:10px;">Articles considered advertisements include those that are solicitations for a business, product or service, or arepublic relations pieces designed to promote a company or individual. Wikispam articles are usually noted fosales-oriented language and external links to a commercial website. However, a differentiation should bemadbetween spam articles and legitima  te articles about commercial ent</p>',
     '</div>',
   '</div>',
   '<div class="two-button2">',
    '<button type="button" class="btn2 btn btn-primary active" onclick="history.go(-2)" >下一题<button>',
    '<button type="button" class="btn4 btn btn-default active" onclick="history.back(-2)" >重做<button>', 
    '</div>',
    '</div>'
  ].join('')
})