'use strict'

define(function(){
  return [
    '<div class="right-part1"> ',
  '<div class="content h650">',
    '<div class="rewr-div">',
     //'<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" class="list-pic">记忆复写</p>',
     '<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" class="list-pic">{{data.xm_title}}</p>',
    '</div>',
    '<hr class="mleft25">',
    '<div class="mid in-block-style">',
    '<div class="in-block">',
     '<div class="b-blue round1 rewrite-style">',
      '<span class="number1">1</span>',
     '</div>',
     '<div class="line1 rebordergreen"></div>',
     '<span class="rewrite-check">查看范文</span>',
    '</div>',
    '<div class="in-block">',
     '<div class="b-blue round1 rewrite-style1">',
      '<span class="number1">2</span>',
     '</div>',
     '<div class="line2 rebordergreen"></div>',
      '<span class="rewrite-read">开始复写</span>',
    '</div>',
    '<div class="in-block">',
     '<div class="b-blue round1 rewrite-style1 rewrite-style3-round">',
      '<span class="number1">3</span>',
     '</div>',
     '<span class="rewrite-write">查看成绩</span>',
    '</div>',
    /* '<div class="in-block">',
     '<div class="b-blue round1 rewrite-style2">',
      '<span class="number1">4</span>',
     '</div>',
      '<span class="rewrite-score">成绩</span>',
     '</div>',*/
      '</div>',
    /* '<hr class="mleft25">',*/
    '<p class="left25 top40 font13">',
      '<span class="num bold">题干：</span>',
      '<span>',
        'Articles considered advertisements include those that are solicitations for a business, product or service, or are public relations pieces designed are public ',
      '</span>',
    '</p>',
    '<hr class="mleft25">',
    '<div class="left25 top40">',
      '<span class="num bold">范文:</span>',
      '<p class="rewrite-span class=" left25""="">',
        'Articles considered advertisements include those that are solicitations for a business, product or service, or are public relations pieces designed are public relations pieces designed are public relations pieces ...',
      '</p>',
      '<span class="right rewrite-span1"><a href="##">查看全文</a></span>',
    '</div>',
    '<hr class="mleft25">',
    '<div class="left25 top35">',
      '<span class="num bold">我的复写：</span>',
      '<div class="rewrite-percent">',
      '<div class="left25 bgreen round-time">',
        '<span class="number">31min</span>',
       '</div>',
       '<div class="left25 bgreen round">',
        '<span class="number">82%</span>',
       '</div>',
       '</div>',
      '<p>',
        '<span>',
          'Articles consired advertisements inclde those that are solications for a business, product or service, or are public relations pieces designed to promote a company or individal ',
        '</span>',
         '<span>',
          'Articles consired advertisements inclde those that are solications for a business, product or service, or are public relations pieces designed to promote a company or individal ',
        '</span>',
         '<span>',
          'Articles consired advertisements inclde those that are solications for a business, product or service, or are public relations pieces designed to promote a company or individal ',
        '</span>',
      '</p>',
    '</div>',
      '<button type="button" class="btn1 btn btn-primary active">下一题</button>',
  '</div>',
  '</div>',
 '</div>'
  ].join('')
})