'use strict'

define(function(){
    return [
       '<div class="h182">',
          '<p class="p3 gray">',
                '<span><a class="bold bread-gray speakjjUnit pointer" data-target="all">全部练习</a><span class="sign1 bread-gray">&gt;</span></span>',
                '<span><a class="bold bread-gray speakjjUnit pointer" data-target="parentMenu">机经口语</a></span><span class="sign1 bread-gray">&gt;</span>',
                '{{if !data.paperExamsYearObj}}',
                    '<span><a class="bold bread-gray speakjjUnit pointer speakjj-forcecast-gray" data-target="jjForecast">机经预测</a></span><span class="sign1 bread-gray">&gt;</span>',
                    '<span><a class="bold tpo-passage">{{data.group_title}} {{data.question.question_sequence_number}}</a></span>',
                '{{else}}',
                    '<span><a class="bold bread-gray speakjjUnit pointer speakjj-paperExams-gray" data-target="jjPaperExams" data-group_id="{{data.paperExamsYearObj.group_id}}">历年真题</a></span><span class="sign1 bread-gray">&gt;</span>',
                    '<span><a class="bold tpo-passage">{{data.paperExamsYearObj.group_title}} {{data.question.question_sequence_number}}</a></span>',
                '{{/if}}',
                '<script type="text/javascript">$("#groupTitle").html("{{data.group_title}}")</script>',
            '</p>',
          '<hr class="mleft25" />',
          '<p class="left25 sentence" id="sentence" content="Do you agree or disagree with the following statement: Professional athletes who receive high salaries, such as football or basketball players, deserve what they have got.">',
          '<span class="bold" style="padding-right:5px;" id="jijing_question_id" category="wjj" jqid="1627" from="exercise">{{data.question.question_sequence_number}}</span>',
          '{{data.question.question_content}}',
            '<div class="mleft10">',
            '<ul class="nav nav-tabs nav-write-tabs" role="tablist" id="myTab">',
            '<li role="presentation" class="active bold">',
            '<a class="tabItem" href="#" data-target="Integralgain" id="IntegralgainTab" role="tab" data-toggle="tab">答案范例</a>',
            '</li>',
            '<li role="presentation" class=" bold">',
            '<a class="tabItem" href="#" data-target="Integraluse" id="IntegraluseTab" role="tab" data-toggle="tab">讲解视频</a>',
            '</li>',
            '</ul>',
            '<div id="tab_record" class="tab-content tpo-write-tab" >',
            '<span id="flashcontent"></span>',
            '<!-- 中部选项卡1-录音控件 -->',
            '<div role="tabpanel" class="tab-pane active" id="Integralgain">',
            '<div class="left25 height90">',
            '{{if data.question.sample_messages}}',
            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{data.question.sample_messages.teacher_avatar }}">',
            '<p>{{data.question.sample_messages.teacher_nickname}}</p>',
            '<img data-audioUrl="{{data.question.sample_messages.sample_content}}" src="../../i/dic-pic.png" class="jijing-speak-dic soundPlay" id="" style="cursor: pointer;">',
            '{{/if}}',
            '</div>',
            '</div>',
            '<!-- 选项卡2-视频播放 -->',
            '<div role="tabpanel" class="tab-pane" id="Integraluse">',
            '{{if data.question.question_analysis}}',
            '<div class="tpo-fun-round jijing-fun-round-video pointer audioPlay" data-source="{{data.question.question_analysis}}"><span class="tpo-span-style1" data-source="{{data.question.question_analysis}}">视频01</span></div>',
            '{{/if}}',
            '</div>',
            '</div>',
            '</div>',
       '</div>',
       '<div class="one-button2">',
          '<button type="button" class="btn btn-primary btn2" id="doAgain">再来一遍</button>',
        '  <button type="button" class="btn btn-primary btn2" id="btnNextQuestion2" data-question_id="{{data.question.next_question_id}}" next_status="{{data.question.next_status}}" category="wjj">下一题</button>',
       '</div>',
       '<div class="h202">',
          '<div>',
             '<p class="p1 bold font14 left25 gray">我的练习记录</p>',
             '<div>',
                '{{each data.question.answers as value index}}',
                   '<hr class="mleft25" />',
                   '<p class="p4 gray font12"><span class="correct-ans">{{value.answer_created_at.substring(0, 19).replace("T", "&nbsp;&nbsp;")}}</span></p>',
                   '<div class="left25">',
                      '<img  style="max-width: 52px; max-height: 52px;width:52px;height:52px;border-radius:26px; position: relative;" src="{{data.userHeadPic}}">',
                      '<img class="soundPlay" data-audioUrl="{{value.answer_audio_url}}" src="../../i/dic-pic.png"  style="cursor: pointer;">',
                   '</div>',
                '{{/each}}',
             '</div>',
          '</div>',
       '</div>'
    ].join('')
})
