'use strict'

define(function(){
  return [
   '<div class="right-part1">',
     '<p class="p3 gray">',
		'<p class="p1 bold black mleft25"><img src="../../i/list-pic.png" class="list-pic"><span>练习报告</span><span class="unit"><a href="#" id="unitVol"></a></span></p>',
    '</p>',
   '<hr class="mleft25" />',

   '<div class="practice-result">',

   '{{if data.rate < 50}}',
    '<img src="../../i/i23.png" class="result-img1" />',
   '{{/if}}',
   '{{if data.rate >= 50 && data.rate <= 80 }}',
    '<img src="../../i/i22.png" class="result-img1" />',
   '{{/if}}',
   '{{if data.rate > 80 && data.rate < 100}}',
    '<img src="../../i/i21.png" class="result-img1" />',
   '{{/if}}',

   '{{if data.rate != 100}}',
    '<div class="i25-1 correctWrong">',
   '{{if data.sectionType=="conversation"}}',
   '<img src="../../i/i25-1.png" style="width: 115px;height: 90px;"/>',
   '{{else}}',
   '<img src="../../i/i25-1.png" />',
   '{{/if}}',
     '<div class="hear-tage">',
      '<p class="bold" style="color:#fff;">{{data.sectionTypeNum}}</p>',
      '<p class="font12" style="color:#fff;">对:{{data.correctCount}}</p>',
      '<p class="font12 marginTop" style="color:#fff;">错:{{data.errorCount}}</p>',
     '</div>',
    '</div>',
   '{{/if}}',
   '</div>',

   '{{if data.rate == 100}}',
    '<img src="../../i/i24.png" style="width:100%;">',
   '{{/if}}',

  '{{if data.rate != 100}}',
   '<nav class="pagination4 center">',
     '{{each data.question_results as value index}}',
      '{{if value.is_correct == 1}}',
        '<span class="page"><a href="##" rel="prev" class="ball-blue">{{value.section_number+1}}</a></span>',
      '{{else}}',
        '<span class="page"><a href="##" rel="prev" class="bred">{{value.section_number+1}}</a></span>',
      '{{/if}}',
     '{{/each}}',
   '</nav>',
  '{{/if}}',

  '{{if data.rate != 100}}',
   '<div class="two-button2">',
    '<button type="button" class="btn btn-primary btn9" data-question_id="{{data.question_id}}" id="againJinJie1">再练一遍</button>',
    '<button type="button" class="btn btn-primary btn2" data-question_id="{{data.question_id}}" data-pickArtical="true" id="errOnlyJinJie1">重做错题</button>',
    //'{{if !data.is_last_question}}',
    //'<button type="button" class="btn btn-primary btn1" id="nextUnitRead" data-next_question_id="{{data.next_question_id}}"  data-next_group_name="{{data.next_group_name}}" data-next_type_name="{{data.next_type_name}}" data-next_rate="{{data.next_rate}}" data-is_last_question="{{data.is_last_question}}">完成</button>',
    //'{{/if}}',
   '{{if !data.isFromPlan}}',
   '<button type="button" class="btn btn-primary btn1" id="showMorePlan">完成</button>',
   '{{/if}}',
   '</div>',

    '{{else}}',
     '<div class="two-button3">',
      '<button type="button" class="btn btn-primary btn9" data-question_id="{{data.question_id}}" id="againJinJie1">再来一遍</button>',
      //'{{if !data.is_last_question}}',
      //'<button type="button" class="btn btn-primary btn1" id="nextUnitRead" data-next_question_id="{{data.next_question_id}}"  data-next_group_name="{{data.next_group_name}}" data-next_type_name="{{data.next_type_name}}" data-next_rate="{{data.next_rate}}" data-is_last_question="{{data.is_last_question}}">完成</button>',
      //'{{/if}}',
   '{{if !data.isFromPlan}}',
   '<button type="button" class="btn btn-primary btn1" id="showMorePlan">完成</button>',
   '{{/if}}',
    '</div>',
   '{{/if}}',
   '<div style="clear:both;"></div>',
  '</div>'
  ].join('')
})
