'use strict'

define(function(){
    return [
		   '<div class="h182">',
		      	'<p class="p3 gray">',
		      		'<img src="../../i/list-pic.png" style="margin-right:10px;vertical-align: -4px;">',
		         	'<span class="bread-gray font18 defaultBlack">{{data.title}}</span>',		 
		         	'<script type="text/javascript">$("#groupTitle").html("{{data.group_title}}")</script>',
		      	'</p>',
		      	'<hr class="mleft25 hr1000" />',
		      	'<p class="left25 sentence" id="sentence">',
		      		'{{data.question.content}}',
		        	'<audio src="{{data.question.audio_url}}" controls="controls" style="display:block;width:100%;height:50px;margin:0 auto;" id="audioAudio">亲 您的浏览器不支持html5的audio标签</audio>',
		        '</p>',   
		       	'{{if data.question.material}}',
		            '<p class="gram-p correct-p"><span><a id="jijingSampleTag" href="#" class="see font-blue ">阅读</a></span></p>',
		            '<div id="jijingSampleDiv" class="ans" style="display: block;">',
		                '<p class="left25 sentence" id="" content="" style="width:93%;">{{data.question.material}}</p>',
		            '</div>',
		        '{{/if}}',
		       	'<div class="mleft10">',
		            '	<ul class="nav nav-tabs nav-write-tabs" style="padding-left:10px;" role="tablist" id="myTab">',
		            '		{{if data.question.analysisAudio.length}}',
		            '		<li role="presentation" class="active">',
		            '			<a class="tabItem font16" href="#" data-target="Integralgain" id="IntegralgainTab" role="tab" data-toggle="tab"><i class="jjWriteTabAudio"></i>答案范例</a>',
		            '		</li>',
		            '		{{/if}}',
		            '		{{if data.question.analysisVideo.length}}',
		            '		<li role="presentation">',
		            '			<a class="tabItem font16" href="#" data-target="Integraluse" id="IntegraluseTab" role="tab" data-toggle="tab"><i class="jjWriteTabVeiod"></i>讲解视频</a>',
		            '		</li>',
		            '		{{/if}}',
		            '		{{if data.question.analysisText.length}}',
		            '		<li role="presentation">',
		            '			<a class="tabItem font16" href="#" data-target="Integralext" id="IntegralextTab" role="tab" data-toggle="tab"><i class="jjWriteTabText"></i>文本范例</a>',
		            '		</li>',
		            '		{{/if}}',
		            '	</ul>',
//		        	'	<hr class="hr1000" style="margin:5px 0 5px 25px"/>',
		        	'<div id="tab_record" class="tab-content tpo-write-tab" style="min-height:100px">',
		                '<!-- 中部选项卡1-录音控件 -->',
			            '<div role="tabpanel" class="tab-pane active" id="Integralgain">',
				            '{{if data.question.analysisAudio}}',
					            '{{each data.question.analysisAudio as value index}}',
						            '<div class="left25 height90">',
							            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{value.teacherAvatar }}">',
							            '<p>{{value.teacherNickname}}</p>',
							            '<img data-audioUrl="{{value.content}}" src="../../i/dic-picg-06.png" class="jijing-speak-dic soundPlay" id="" style="cursor: pointer;">',
						            '</div>',
					            '{{/each}}',
				            '{{/if}}',
			            '</div>',
			            '<!-- 选项卡2-视频播放 -->',
			            '<div role="tabpanel" class="tab-pane" id="Integraluse">',
				            '{{if data.question.analysisVideo}}',
					            '{{each data.question.analysisVideo as value index}}',
					            	'<div class="tpo-fun-round jijing-fun-round-video pointer audioPlay" data-source="{{value.content}}"><span class="tpo-span-style1" data-source="{{value.content}}">视频{{index+1}}</span></div>',
					            '{{/each}}',
				            '{{/if}}',
			            '</div>',
			            '<!-- 选项卡3-文本解析 -->',
			            '<div role="tabpanel" class="tab-pane" id="Integralext">',
				            '{{if data.question.analysisText}}',
					            '{{each data.question.analysisText as value index}}',
						            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{value.teacherAvatar }}">',
						            '<p>{{value.teacherNickname}}</p>',
						            '<p class="analysisContent-box">',
						            	'<span class="analysisContent">{{value.content}}</span>',
						            	'<span class="show_hidden">展开</span>',
						            '</p>',
					            '{{/each}}',
				            '{{/if}}',
			            '</div>',       
		        	'</div>',
		        '</div>',
			'</div>',
	        '<div class="h202">',
	            '<div style="width: 100%;height:40px;"></div>',
	          	'<div id="tab_record" class="tab-content tpo-write-tab" >',
                	'<span id="flashcontent"></span>',
                  	'<div class="repeat-record">',
						'<p id="recordTimerP" style="display: none;"><span id="recordTimer">00:00</span>/<span id="recordTotalLength"></span></p>',
						'<p id="recordTipP"><span id="recordTip">请点击开始录音</p>',
						'<div><!--开始录音--><img id="startRecord" src="../../i/share/ic-record-start.png" class="repeat-pic10 pointer">',
                      	'<!--录音中--><img id="recording" style="padding-top:8px;" src="../../i/share/repeat-pic6.gif" class="repeat-pic10 pointer">',
                      	'<!--播放录音--><img id="playRecord" src="../../i/share/ic-record-stop-play.png" class="repeat-pic10 pointer">',
                      	'<!--播放中--><img id="playingRecord" src="../../i/share/ic-record-stop.png" class="repeat-pic10"></div>',
               		'</div>',
                   	'<div class="two-button2">',
	                    '<button type="button" class="btn9 btn btn-primary active" id="speak-reRecord" disabled>重录</button>',
	                    '<button type="button" class="btn1 btn btn-primary active" id="speak-saveRecord" disabled>保存</button>',
	                    '<form id="uploadForm" name="uploadForm" method="post" action="{{data.uploadUrl}}" enctype="multipart/form-data">',
		                    '<input name="audio_length" id="audio_length" type="hidden" value="">',
		                    '<input name="question_id" id="question_id" type="hidden" value="">',
		                    '<input name="is_share" id="is_share" type="hidden" value="">',     //20160920
			               	'<input name="planDayId" id="planDayId" type="hidden" value="">',   //20160920
			                '<input name="exerciseId" id="exerciseId" type="hidden" value="">', //20160920
			                '<input name="startTime" id="startTime" type="hidden" value="">',   //20160920
			                '<input name="endTime" id="endTime" type="hidden" value="">',       //20160920
                      	'</form>',
                    '</div>',
	        	'</div>',
        	'</div>',
        	'<div class="h202">',
        		//我的录音部分------
		        '<div style="padding:20px;">',
             		'<p class="bold" style="padding-left:5px; font-size:15px"><img src="../i/al/sp2.jpg" alt="" style="margin-right:10px;vertical-align:-4px">我的回答</p>',
	             	'<div>',
	             		'{{if data.question.question_answers.length <= 0}}',
	             		'<p class="no_record" style="padding-left:25px">您暂时还没有录音~</p>',
	             		'{{else}}',
	             		'<hr class="hr1000" style="border-color:#dcdcdc!important;" />',
	                	'{{each data.question.question_answers as value index}}',	        
		                   	'<p class="p4 gray font12"><span class="correct-ans">{{value.answer_created_at}}</span></p>',
		                   	'<div class="left25">',
		                      	'<span class="font-right" style="left:160px;top:2px;">{{value.answer_audio_length+"\'"}}</span>',
		                      	'<img  style="max-width: 52px; max-height: 52px;width:52px;height:52px;border-radius:26px; position: relative;" src="{{data.userHeadPic}}">',
		                      	'<img class="soundPlay" data-audioUrl="{{value.answer_audio_url}}" src="../../i/dic-pic.png"  style="cursor: pointer;">',
		                   	'</div>',
		                   	'<div class="speak-share-cutline"></div>',
	                	'{{/each}}',
	                	'{{/if}}',
	             	'</div>',
	          	'</div>',
        	'</div>'

    ].join('')
})
