'use strict'

define(function(){
    return [
       '<div class="h182">',
          '<p class="p3 gray">',
				'<span class="bold bread-gray">{{data.title}}</span>',//20160926
                '<span><a href="javascript:;" class="bold pointer" id="share_btn" data-target="parentMenu">更多记录>></a></span>',/*9-29日 添加更多记录  按钮*/
                '<script type="text/javascript">$("#groupTitle").html("{{data.group_title}}")</script>',
            '</p>',
          	'<hr class="mleft25" />',
          	'<p class="left25 sentence" id="sentence" content="Do you agree or disagree with the following statement: Professional athletes who receive high salaries, such as football or basketball players, deserve what they have got.">',
			'{{data.question.content}}',
            '<div class="mleft10">',
            '<ul class="nav nav-tabs nav-write-tabs" role="tablist" id="myTab">',
            '{{if data.question.analysisAudio.length}}',
            '	<li role="presentation" class="active bold">',
            '		<a class="tabItem" href="#" data-target="Integralgain" id="IntegralgainTab" role="tab" data-toggle="tab">答案范例</a>',
            '	</li>',
            '{{/if}}',
            '{{if data.question.analysisVideo.length}}',
            '	<li role="presentation" class=" bold">',
            '		<a class="tabItem" href="#" data-target="Integraluse" id="IntegraluseTab" role="tab" data-toggle="tab">讲解视频</a>',
            '	</li>',
            '{{/if}}',
            '{{if data.question.analysisText.length}}',
            '	<li role="presentation" class=" bold">',
            '		<a class="tabItem" href="#" data-target="Integralext" id="IntegralextTab" role="tab" data-toggle="tab">文本范例</a>',
            '	</li>',
            '{{/if}}',
            '</ul>',
            '<div id="tab_record" class="tab-content tpo-write-tab"  style="min-height:90px;">',
	            '<!-- 中部选项卡1-录音控件 -->',
	            '<div role="tabpanel" class="tab-pane active" id="Integralgain">',
		            '{{if data.question.analysisAudio}}',
			            '{{each data.question.analysisAudio as value index}}',
				            '<div class="left25 height90">',
					            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{value.teacherAvatar }}">',
					            '<p>{{value.teacherNickname}}</p>',
					            '<img data-audioUrl="{{value.content}}" src="../../i/dic-pic.png" class="jijing-speak-dic soundPlay" id="" style="cursor: pointer;">',
				            '</div>',
			            '{{/each}}',
		            '{{/if}}',
	            '</div>',
	            '<!-- 选项卡2-视频播放 -->',
	            '<div role="tabpanel" class="tab-pane" id="Integraluse">',
		            '{{if data.question.analysisVideo}}',
			            '{{each data.question.analysisVideo as value index}}',
			            	'<div class="tpo-fun-round jijing-fun-round-video pointer audioPlay" data-source="{{value.content}}"><span class="tpo-span-style1" data-source="{{value.content}}">视频{{index+1}}</span></div>',
			            '{{/each}}',
		            '{{/if}}',
	            '</div>',
	            '<!-- 选项卡3-文本解析 -->',
	            '<div role="tabpanel" class="tab-pane" id="Integralext">',
		            '{{if data.question.analysisText}}',
			            '{{each data.question.analysisText as value index}}',
				            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{value.teacherAvatar }}">',
				            '<p>{{value.teacherNickname}}</p>',
				            '<p>',
				            	'<span class="analysisContent">{{value.content}}</span>',
				            	'<span class="show_hidden">展开</span>',
				            '</p>',
			            '{{/each}}',
		            '{{/if}}',
	            '</div>',
            '</div>',
            '</div>',
       	'</div>',
       	'<div class="one-button2">',
          	'<button type="button" class="btn btn-primary btn2" id="doReordAgain">再来一遍</button>',
			'<button type="button" class="btn btn-primary btn2" id="btnDoneQuestion2" style="color:#509BFD">完成</button>',
       	'</div>',
       	'<div class="h202">',
          	'<div>',
             	'<p class="p1 bold font14 left25 gray">我的录音</p>',
             	'<div>',
                '{{each data.question.results as value index}}',
                   '<hr class="mleft25" />',
                   '<p class="p4 gray font12" style="margin-left:0"><span class="correct-ans">{{value.created_at}}</span>',
                   '{{if value.is_share == 1}}',
                   '<span class="isShare_tips" style="color:#008000; margin-left:-532px">[已发布]</span>',
                   '{{else}}',
                   '<span class="isShare_tips" style="color:#008000; margin-left:-532px">[未发布]</span>',
                   '{{/if}}',
                   '</p>',
                   '<div class="left25">',
                   		'<span class="font-right">{{value.audio_length+"\'"}}</span>',
                    	'<img  style="max-width: 52px; max-height: 52px;width:52px;height:52px;border-radius:26px; position: relative;" src="{{data.userHeadPic}}">',
                    	'<img class="soundPlay" data-audioUrl="{{value.content}}" src="../../i/dic-pic.png"  style="cursor: pointer;">',
                   		'{{if value.is_share == 1}}',
                   		'<a href="javascript:;" id="speak-share" result_id={{value.result_id}} style="display:inline-block; height: 30px;line-height: 30px;',
                   		'font-size: 14px;color: #fff;width: 80px;cursor: pointer;text-align: center;background: #999; vertical-align:middle; border-radius:5px;margin-left:30px">取消发布</a>',
                   		'{{else}}',
				        '<a href="javascript:;" id="speak-share" result_id={{value.result_id}} style="display:inline-block; height: 30px;line-height: 30px;',
				        'font-size: 14px;color: #fff;width: 80px;cursor: pointer;text-align: center;background: #509BFD; vertical-align:middle; border-radius:5px;margin-left:30px">发布</a>',
				        '{{/if}}',
                   '</div>',
                '{{/each}}',
             '</div>',
          '</div>',
       '</div>'
    ].join('')
})
