'use strict'

define(function(){
  return [
       // '<div class="left25 font13 repeat-div3">',
       //   '<span class="num repeat-num pointer" id="questionsTabToggle">{{data.currentQuestionIndex+1}}/{{data.questionsLength}}<span class="caret2 pointer" style="color: #929292;" id="nameSanJiao"></span></span>',
       //   '<div class="tpo-points1 " id="questionsTab" style="clear:both; display: none;">',
       //   '<p class="tpo-piece">',
       //   '</p>',
       //  // '<a href="#" class="point-round-style">1</a>',
       //  '{{each data.questionsNum as value index}}',
       //  '{{if data.currentQuestionIndex+1 == value}}',
       //    '<a href="###" class="questionPageTabErr point-round-style" data-localIndex={{index}} data-pageNum={{value-1}}>{{value}}</a>',
       //  '{{else}}',
       //    '<a href="###" class="questionPageTabErr" data-localIndex={{index}} data-pageNum={{value-1}}>{{value}}</a>',
       //  '{{/if}}',
       //  '{{/each}}',
       // '</div>',
       //   '<p class="tpo-senten"><a score="0" class="item sim-a questionBrContent" answer_i="" sequence_number="1"></a></p>',

       //  '{{if data.question.questionType == "complex"}}',
       //   '<p class="tpo-senten tpo-complex-ques">{{data.question.G1.p}}</p>',
       //   '<p class="tpo-senten tpo-complex-choice" id="g1Answer">',
       //   '{{each data.question.simpleChoices as value index}}',
       //   '<span class="tpo-choice-round pointer complexChoice showEnable" data-answer="{{value.identifier}}">{{value.identifier}}</span><span class="tpo-choice-round showDisable" style="display: none;">{{value.identifier}}</span>',
       //   '{{/each}}',
       //   '</p>',

       //   '<p class="tpo-senten tpo-complex-ques">{{data.question.G2.p}}</p>',
       //   '<p class="tpo-senten tpo-complex-choice" id="g2Answer">',
       //   '{{each data.question.simpleChoices as value index}}',
       //   '<span class="tpo-choice-round pointer complexChoice showEnable" data-answer="{{value.identifier}}">{{value.identifier}}</span><span class="tpo-choice-round showDisable" style="display: none;">{{value.identifier}}</span>',
       //   '{{/each}}',
       //   '</p>',
       //  '{{/if}}',

       //  '</div>',
       //   '<table class="table1 mleft25 tpo-table newtop" cellpadding="0" cellspacing="0" id="singMul">',

       //   '{{if data.question.questionType == "single"}}',
       //   '{{each data.question.simpleChoices as value index}}',
       //    '<tr>',
       //     '<td class="td1 word-layout2"><span class="tpo-choice-round pointer singleChoice showEnable newtop-top" data-answer="{{value.identifier}}">{{value.identifier}}</span><span class="tpo-choice-round showDisable newtop-top" style="display: none;">{{value.identifier}}</span></td>',
       //     '<td class="newtpo-table">{{value.choiceOption}}</td>',
       //    '</tr>',
       //   '{{/each}}',
       //   '{{/if}}',

       //   '{{if data.question.questionType == "multiple"}}',
       //   '{{each data.question.simpleChoices as value index}}',
       //    '<tr>',
       //     '<td class="td1 word-layout2"><span class="tpo-choice-round pointer multipleChoice showEnable newtop-top"  data-answer="{{value.identifier}}">{{value.identifier}}</span><span class="tpo-choice-round showDisable newtop-top" style="display: none;">{{value.identifier}}</span></td>',
       //     '<td class="newtpo-table">{{value.choiceOption}}</td>',
       //    '</tr>',
       //   '{{/each}}',
       //   '{{/if}}',

       //   '{{if data.question.questionType == "complex"}}',
       //   '{{each data.question.simpleChoices as value index}}',
       //    '<tr>',
       //     '<td class="td1 word-layout2">{{value.identifier}}</td>',
       //     '<td class="newtpo-table">{{value.choiceOption}}</td>',
       //    '</tr>',
       //   '{{/each}}',
       //   '{{/if}}',

       //  '</table>',
       //  '<div>',
       //    '<a href="###" class="Previous tpo-page" id="preQuestionErr" style="display: none;"><span class="arrow-left"></span></a>',
       //    '<a href="###" class="Next tpo-page" id="nextQuestionErr"><span class="arrow-right"></span></a>',
       //  '</div>'
       


       '     <div class="left25 font13">',
          '       <span class="num repeat-num pointer" id="questionsTabToggle">{{data.currentQuestionIndex+1}}/{{data.questionsLength}}<span class="caret2 pointer" style="color: #929292;" id="nameSanJiao"></span></span>',
                  '<div class="tpo-points1 " id="questionsTab" style="clear:both; display: none;">',
                      '<p class="tpo-piece">',
                      '</p>',
                      '{{each data.questionsNum as value index}}',
                      '{{if data.currentQuestionIndex+1 == value}}',
                        '<a href="###" class="questionPageTabErr point-round-style" data-localIndex={{index}} data-pageNum={{value-1}}>{{value}}</a>',
                      '{{else}}',
                        '<a href="###" class="questionPageTabErr" data-localIndex={{index}} data-pageNum={{value-1}}>{{value}}</a>',
                      '{{/if}}',
                      '{{/each}}',
                  '</div>',

          '        <div class="N_font_b fright mright25 mbot15 N_c_p">',
          '           <span class="mright10"><span class="N_tpoicon N_ticon_speak" style="cursor: auto;"></span><a class="all-blue font14 img_font_m" id="seeJiangjie">讲解</a></span>',
          '           <span><span class="N_tpoicon N_ticon_jx" style="cursor: auto;"></span><a class="all-blue font14 img_font_m" id="seeJieXiReadErr">解析</a></span>',
          '        </div>              ',
          '      </div>',



          '     <div class="Ntpo_left_p">',
          '        <p class="" id="articleP"><a score="0" class="item sim-a questionBrContent" style="text-decoration:none;" answer_i="" sequence_number="1"></a></p>',
         '{{if data.question.questionType == "complex"}}',
         // '<p class="tpo-senten tpo-complex-ques">{{data.question.G1.p}}</p>',
         // '<p class="tpo-senten tpo-complex-choice" id="g1Answer">',
         // '{{each data.question.simpleChoices as value index}}',
         // '<span class="tpo-choice-round pointer complexChoice showEnable" data-answer="{{value.identifier}}">{{value.identifier}}</span><span class="tpo-choice-round showDisable" style="display: none;">{{value.identifier}}</span>',
         // '{{/each}}',
         // '</p>',

         // '<p class="tpo-senten tpo-complex-ques">{{data.question.G2.p}}</p>',
         // '<p class="tpo-senten tpo-complex-choice" id="g2Answer">',
         // '{{each data.question.simpleChoices as value index}}',
         // '<span class="tpo-choice-round pointer complexChoice showEnable" data-answer="{{value.identifier}}">{{value.identifier}}</span><span class="tpo-choice-round showDisable" style="display: none;">{{value.identifier}}</span>',
         // '{{/each}}',
         // '</p>',
           '<div class="N_tpo_tab">',
            ' <div class="N_tpol_tab grayf2" id="g1Div"><span>{{data.question.G1.p}}</span><BR><span id="g1AnswerDiv"></span></div>',
            ' <div class="N_tpor_tab" id="g2Div"><span>{{data.question.G2.p}}</span><BR><span id="g2AnswerDiv"></span></div>',
            ' <div class="triangle-borderl_l tb-border sanjiao"></div>',
            ' <div class="triangle-borderl_l tb-background sanjiao"></div>',
           '</div>',
        '{{/if}}',

        // '</div>',
         '<table class="table1 N_tpo-table newtop " cellpadding="0" cellspacing="0" id="singMul">',
         '<tbody>',
         '{{if data.question.questionType == "single"}}',
         '{{each data.question.simpleChoices as value index}}',
          '<tr>',
           '<td class="td1 word-layout2"><span class="tpo-choice-round pointer singleChoice showEnable newtop-top" data-answer="{{value.identifier}}">{{value.identifier}}</span><span class="tpo-choice-round showDisable newtop-top" data-answer="{{value.identifier}}" style="display: none;">{{value.identifier}}</span></td>',
           '<td class="newtpo-table">{{value.choiceOption}}</td>',
          '</tr>',
         '{{/each}}',
         '{{/if}}',

         '{{if data.question.questionType == "multiple"}}',
         '{{each data.question.simpleChoices as value index}}',
          // '<tr>',
          //  '<td class="td1 word-layout2"><span class="tpo-choice-round pointer multipleChoice showEnable newtop-top" data-answer="{{value.identifier}}">{{value.identifier}}</span><span class="tpo-choice-round showDisable newtop-top" style="display: none;">{{value.identifier}}</span></td>',
          //  '<td class="newtpo-table">{{value.choiceOption}}</td>',
          // '</tr>',
          '<tr>',
          ' <td class="td1 word-layout2">',
          '  <span class="N_tpo_c_square pointer multipleChoice showEnable " data-answer="{{value.identifier}}">{{value.identifier}}</span>',
          '  <span class="N_tpo_c_square_hide showDisable " data-answer="{{value.identifier}}" style="display: none;">{{value.identifier}}</span>',
          ' </td>',
          ' <td class="newtpo-table">{{value.choiceOption}}</td>',
          '</tr>',
         '{{/each}}',
         '{{/if}}',

         '{{if data.question.questionType == "complex"}}',
         '{{each data.question.simpleChoices as value index}}',
          // '<tr>',
          //  '<td class="td1 word-layout2">{{value.identifier}}</td>',
          //  '<td class="newtpo-table">{{value.choiceOption}}</td>',
          // '</tr>',
            '<tr class="answerTr1">',
            ' <td class="td1 word-layout2">',
            '  <span class="N_tpo_c_square pointer complexChoice1 showEnable " data-answer="{{value.identifier}}">{{value.identifier}}</span>',
            '  <span class="N_tpo_c_square_hide showDisable " data-answer="{{value.identifier}}" style="display: none;">{{value.identifier}}</span>',
            ' </td>',
            ' <td class="newtpo-table N_c_fy">{{value.choiceOption}}</td>',
            '</tr>',
         '{{/each}}',
         '{{each data.question.simpleChoices as value index}}',
            '<tr class="answerTr2" style="display: none;">',
            ' <td class="td1 word-layout2">',
            '  <span class="N_tpo_c_square pointer complexChoice2 showEnable " data-answer="{{value.identifier}}">{{value.identifier}}</span>',
            '  <span class="N_tpo_c_square_hide showDisable " data-answer="{{value.identifier}}" style="display: none;">{{value.identifier}}</span>',
            ' </td>',
            ' <td class="newtpo-table N_c_fy">{{value.choiceOption}}</td>',
            '</tr>',
         '{{/each}}',
         '{{/if}}',
         '</tbody>',
        '</table>',
          '<div class="N_tpofont_jx font12" style="display:none;" id="tpoReadJieXi">',
          '   <hr class="N_tpohr" style="margin-top:0px;" />',
          '   <p class="">',
          '     <span class="pg_red mright10" id="yourAnswerDiv">你的答案 : <span class="" id="yourAnswer"></span></span>',
          '     <span  class="green6bc">正确答案 : <span>{{data.question.correctResponse}}</span></span>',
          '   </p>',
          '   <p class="N_tpo-points" style="">{{data.question.p}}</p>',
          ' </div>',
          ' <div>',
          '   <a href="###" class="N_before N_tpo-page" id="preQuestionErr" style="display: block;"><span class="arrow-left"></span></a>',
          '   <a href="###" class="N_after N_tpo-page" id="nextQuestionErr"><span class="arrow-right"></span></a>',
          ' </div>',
          '</div>',
                 /**视频部分**/
       '<div class="modal fade" id="audioPlayModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">',
            // '<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>',
          '<div class="modal-dialog jinjievideo-style">',
                '<button type="button" class="mtop10 close jinjievideo-close" data-dismiss="modal"><img src="../../i/N_close.png" /></button>',
                '<ul class="N_viedo_tab" >',
                 '{{if data.question.audio.length < 10}}',
                  '{{each data.question.audio as value index}}',
                   '<li class="blue509" >',
                      '{{if index == 0}}',
                          '<span class=""><a class="jiexiAudio N_V_active N_tpoicons all-blue font14 img_font_m" data-source="{{value}}" data-index={{index}}>讲解{{index+1}}</a></span>',
                       '{{else}}',
                          '<span class=""><a class="jiexiAudio N_tpoicons all-blue font14 img_font_m" data-source="{{value}}" data-index={{index}}>讲解{{index+1}}</a></span>',
                      '{{/if}}',
                   '</li>',
                  '{{/each}}',
                 '{{else}}',
                   '<li class="blue509" >',
                       '<span class=""><a class="jiexiAudio N_V_active N_tpoicons all-blue font14 img_font_m" data-source="{{data.question.audio}}" data-index="0">讲解1</a></span>',
                   '</li>',
                 '{{/if}}',
                '</ul>',
                '<div id="audioPlayDiv" style="height: 400px;">',
                '</div>',
          '</div>',
        '</div>'
  ].join('')
})
