'use strict'

define(function(){
    return [
		    '<div class="h182">',
		        '<p class="p3 gray">',
		           	'<span class="bold bread-gray">{{data.title}}</span>',
		            '<script type="text/javascript">$("#groupTitle").html("{{data.group_title}}")</script>',
		        '</p>',
		        '<hr class="mleft25" />',
		        '<p class="left25 sentence" id="sentence">',
		        '{{data.question.question_content}}',
		        '<audio src="{{data.question.audio_url}}" controls="controls" style="width:720px;height:50px;" id="audioAudio">亲 您的浏览器不支持html5的audio标签</audio>',
		        '{{if data.question.material}}',
		        	'<p class="gram-p correct-p"><span><a id="jijingSampleTag" href="#" class="see font-blue ">阅读</a></span></p>',
		            '<div id="jijingSampleDiv" class="ans" style="display: block;">',
		            	'<p class="left25 sentence" id="" content="" style="width:93%;">{{data.question.material}}</p>',
		            '</div>',
		        '{{/if}}',
	            '<div class="mleft10">',
		            '<ul class="nav nav-tabs nav-write-tabs" role="tablist" id="myTab">',
			            '{{if data.question.analysisAudio.length}}',
			            '	<li role="presentation" class="active bold">',
			            '		<a class="tabItem" href="#" data-target="Integralgain" id="IntegralgainTab" role="tab" data-toggle="tab">答案范例</a>',
			            '	</li>',
			            '{{/if}}',
			            '{{if data.question.analysisVideo.length}}',
			            '	<li role="presentation" class=" bold">',
			            '		<a class="tabItem" href="#" data-target="Integraluse" id="IntegraluseTab" role="tab" data-toggle="tab">讲解视频</a>',
			            '	</li>',
			            '{{/if}}',
			            '{{if data.question.analysisText.length}}',
			            '	<li role="presentation" class=" bold">',
			            '		<a class="tabItem" href="#" data-target="Integralext" id="IntegralextTab" role="tab" data-toggle="tab">文本范例</a>',
			            '	</li>',
			            '{{/if}}',
	            	'</ul>',
                	'<div id="tab_record" class="tab-content tpo-write-tab" style="min-height:100px">',
		                '<!-- 中部选项卡1-录音控件 -->',
			            '<div role="tabpanel" class="tab-pane active" id="Integralgain">',
				            '{{if data.question.analysisAudio}}',
					            '{{each data.question.analysisAudio as value index}}',
						            '<div class="left25 height90">',
							            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{value.teacherAvatar }}">',
							            '<p>{{value.teacherNickname}}</p>',
							            '<img data-audioUrl="{{value.content}}" src="../../i/dic-pic.png" class="jijing-speak-dic soundPlay" id="" style="cursor: pointer;">',
						            '</div>',
					            '{{/each}}',
				            '{{/if}}',
			            '</div>',
			            '<!-- 选项卡2-视频播放 -->',
			            '<div role="tabpanel" class="tab-pane" id="Integraluse">',
				            '{{if data.question.analysisVideo}}',
					            '{{each data.question.analysisVideo as value index}}',
					            	'<div class="tpo-fun-round jijing-fun-round-video pointer audioPlay" data-source="{{value.content}}"><span class="tpo-span-style1" data-source="{{value.content}}">视频{{index+1}}</span></div>',
					            '{{/each}}',
				            '{{/if}}',
			            '</div>',
			            '<!-- 选项卡3-文本解析 -->',
			            '<div role="tabpanel" class="tab-pane" id="Integralext">',
				            '{{if data.question.analysisText}}',
					            '{{each data.question.analysisText as value index}}',
						            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{value.teacherAvatar }}">',
						            '<p>{{value.teacherNickname}}</p>',
						            '<p>',
						            	'<span class="analysisContent">{{value.content}}</span>',
						            	'<span class="show_hidden">展开</span>',
						            '</p>',
					            '{{/each}}',
				            '{{/if}}',
			            '</div>',       
                	'</div>',
            	'</div>',
      		'</div>',

       	'<div class="one-button2">',
          	'<button type="button" class="btn btn-primary btn2" id="doReordAgain">再来一遍</button>',
		  	'<button type="button" class="btn btn-primary btn2" id="btnDoneQuestion2" style="color:#509BFD">完成</button>',
       	'</div>',
       	'<div class="h202">',
          	'<div>',
             	'<p class="p1 bold font14 left25 gray">我的录音</p>',
             	'<div>',
                	'{{each data.question.question_answers as value index}}',
                   	'<hr class="mleft25" style="clear:both;" />',
                   	'<p class="p4 gray font12"><span class="correct-ans">{{value.answer_created_at}}</span></p>',
                   	'<div class="left25">',
                      	'<span class="font-right">{{value.answer_audio_length+"\'"}}</span>',
                      	'<img  style="max-width: 52px; max-height: 52px;width:52px;height:52px;border-radius:26px; position: relative;" src="{{data.userHeadPic}}">',
                      	'<img class="soundPlay" data-audioUrl="{{value.answer_audio_url}}" src="../../i/dic-pic.png"  style="cursor: pointer;">',
                   	'</div>',
                	'{{/each}}',
             	'</div>',
          	'</div>',
       	'</div>'
    ].join('')
})
