'use strict'

define(function(){
    return [
       	'<div class="h182" style="">',
          	'<p class="p3 gray">',
          		'<img src="../../i/list-pic.png" style="margin-right:10px;vertical-align: -4px;">',
		 		'<span class="bread-gray font18 defaultBlack">{{data.title}}</span>',   //20160926
         		'<span><a href="javascript:;" class="pointer" id="share_btn" data-target="parentMenu">更多记录>></a></span>',/*9-5日 添加分享记录  按钮*/
             	'<script type="text/javascript">$("#groupTitle").html("{{data.group_title}}")</script>',
          	'</p>',
          	'<hr class="mleft25 hr1000" />',
          	'<p class="left25 sentence" id="sentence" content="Do you agree or disagree with the following statement: Professional athletes who receive high salaries, such as football or basketball players, deserve what they have got.">',
          	//'	<span class="bold" style="padding-right:5px;" id="jijing_question_id" category="wjj" jqid="1627" from="exercise">{{data.question.sequence_number}}</span>',
          	'{{data.question.content}}',
          	'</p>',
          	'<div class="two-button">',
          		'<button id="start_btn" class="btn btn1" style="margin-bottom:20px;">开始录音</button>',
          	'</div>',
          	
          	'<div class="tab-content tpo-write-tab" id="speak_h202" style="display:none;" >',
         		'<span id="flashcontent"></span>',
                '<div class="repeat-record">',
                     '<p id="recordTimerP" style="display: none;"><span id="recordTimer" >00:00</span>/<span id="recordTotalLength">00:45</span></p>',
                     '<p id="recordTipP"><span id="recordTip">请点击开始录音</p>',
                      '<div><!--开始录音--><img id="startRecord" src="../../i/share/ic-record-start.png" class="repeat-pic10 pointer">',
                      '<!--录音中--><img id="recording" style="padding-top:8px;" src="../../i/share/repeat-pic6.gif" class="repeat-pic10 pointer">',
                      '<!--播放录音--><img id="playRecord" src="../../i/share/ic-record-stop-play.png" class="repeat-pic10 pointer">',
                      '<!--播放中--><img id="playingRecord" src="../../i/share/ic-record-stop.png" class="repeat-pic10"></div>',
               '</div>',
               '<div class="two-button2">',
                  '<button type="button" class="btn9 btn btn-primary active" id="speak-reRecord" disabled>重录</button>',
                  '<button type="button" class="btn1 btn btn-primary active" id="speak-saveRecord" disabled>保存</button>',

                  '<form id="uploadForm" name="uploadForm" method="post" action="{{data.uploadUrl}}" enctype="multipart/form-data">',
                  '    <input name="audio_length" id="audio_length" type="hidden" value="">',
                  '    <input name="question_id" id="question_id" type="hidden" value="">',
                  '    <input name="is_share" id="is_share" type="hidden" value="">',     //20160920
               	  '    <input name="planDayId" id="planDayId" type="hidden" value="">',   //20160920
                  '    <input name="exerciseId" id="exerciseId" type="hidden" value="">', //20160920
                  '    <input name="startTime" id="startTime" type="hidden" value="">',   //20160920
                  '    <input name="endTime" id="endTime" type="hidden" value="">',       /*//20160920*/
                  '</form>',
               '</div>',
          	'</div>',
     	'</div>',
     	
     	'{{if data.question.analysisAudio.length || data.question.analysisVideo.length || data.question.analysisText.length}}',
     	'<div  class="h202" style="margin-bottom: 20px;">',
      		'<div class="mleft10">',
            '	<ul class="nav nav-tabs nav-write-tabs" style="padding-left:10px;" role="tablist" id="myTab">',
            '		{{if data.question.analysisAudio.length}}',
            '		<li role="presentation" class="active">',
            '			<a class="tabItem font16" href="#" data-target="Integralgain" id="IntegralgainTab" role="tab" data-toggle="tab"><i class="jjWriteTabAudio"></i>答案范例</a>',
            '		</li>',
            '		{{/if}}',
            '		{{if data.question.analysisVideo.length}}',
            '		<li role="presentation">',
            '			<a class="tabItem font16" href="#" data-target="Integraluse" id="IntegraluseTab" role="tab" data-toggle="tab"><i class="jjWriteTabVeiod"></i>讲解视频</a>',
            '		</li>',
            '		{{/if}}',
            '		{{if data.question.analysisText.length}}',
            '		<li role="presentation">',
            '			<a class="tabItem font16" href="#" data-target="Integralext" id="IntegralextTab" role="tab" data-toggle="tab"><i class="jjWriteTabText"></i>文本范例</a>',
            '		</li>',
            '		{{/if}}',
            '	</ul>',
            '	<hr class="hr1000" style="margin:5px 0 5px 25px"/>',
            '	<div id="tab_record" class="tab-content tpo-write-tab"  style="min-height:20px;">',
		            '<!-- 中部选项卡1-录音控件 -->',
		            '{{if data.question.analysisAudio.length}}',
			            '<div role="tabpanel" class="tab-pane active" id="Integralgain">',
				            '{{each data.question.analysisAudio as value index}}',
					            '<div class="left25 height90">',
						            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{value.teacherAvatar }}">',
						            '<p>{{value.teacherNickname}}</p>',
						            '<img data-audioUrl="{{value.content}}" src="../../i/dic-pic.png" class="jijing-speak-dic soundPlay" id="" style="cursor: pointer;">',
					            '</div>',
				            '{{/each}}',			            
			            '</div>',
		            '{{/if}}',
		            '<!-- 选项卡2-视频播放 -->',
		            '{{if data.question.analysisVideo.length}}',
			            '<div role="tabpanel" class="tab-pane" id="Integraluse">',
				            '{{each data.question.analysisVideo as value index}}',
				            	'<div class="tpo-fun-round jijing-fun-round-video pointer audioPlay" data-source="{{value.content}}"><span class="tpo-span-style1" data-source="{{value.content}}">视频{{index+1}}</span></div>',
				            '{{/each}}',
			            '</div>',
		            '{{/if}}',
		            '<!-- 选项卡3-文本解析 -->',
		            '{{if data.question.analysisText.length}}',
			            '<div role="tabpanel" class="tab-pane" id="Integralext">',
				            '{{each data.question.analysisText as value index}}',
					            '<img style="max-width: 53px;max-height: 53px;width:52px;height:52px;border-radius:26px;margin-bottom:5px;" src="{{value.teacherAvatar }}">',
					            '<p>{{value.teacherNickname}}</p>',
					            '<p class="analysisContent-box">',
					            	'<span class="analysisContent">{{value.content}}</span>',
					            	'<span class="show_hidden">展开</span>',
					            '</p>',
				            '{{/each}}',
			            '</div>',
		            '{{/if}}',
            	'</div>',
            '</div>',
        '</div>',
        '{{/if}}',
        '<div class="h202">',
          //我的录音部分------
	        '<div class="tpo_share" style="padding:20px;">',
	        	'<p class="bold" style="padding-left:5px; font-size:15px"><img src="../i/al/sp2.jpg" alt="" style="margin-right:10px;vertical-align:-4px">我的回答</p>',
		        '{{if data.question.results.length <= 0}}',
		    		'<p class="no_record" style="padding-left:25px">您暂时还没有录音~</p>',
		    	'{{else}}',
		    		'<hr class="hr1000" style="border-color:#dcdcdc!important;" />',
		        	'{{each data.question.results as value index}}',
		               	'<p class="p4 gray font12" style="margin-left:0"><span class="correct-ans">{{value.created_at}}</span>',
		               	'</p>',
		               	'<div class="left25" style="position:relative;">',
		               		'<span class="font-right" style="left:160px;top:2px;">{{value.audio_length+"\'"}}</span>',
		                	'<img  style="max-width: 52px; max-height: 52px;width:52px;height:52px;border-radius:26px; position: relative;" src="{{data.userHeadPic}}">',
		                	'<img class="soundPlay" data-audioUrl="{{value.content}}" src="../../i/dic-picg-06.png"  style="cursor: pointer;">',
		               		'{{if value.is_share == 1}}',
		               		'<a class="have-share" result_id={{value.result_id}}>',
		               			'<i class="release_icon" style=display:none></i>',
			               		'已发布',
			               		'<i class="share-down-arrow"></i>',
			               		'<i class="share-up-arrow" style="display:none"></i>',	               		
			               		'<span class="speak-share-cancle" style="display:none;">取消发布</span>',
		               		'</a>',
						    '<a class="speak-share" result_id={{value.result_id}} style="display:none;>',
					        	'<i class="release_icon"></i>',
			               		'发布',
			               	'</a>',
		               		'{{else}}',
		               		'<a class="have-share" result_id={{value.result_id}} style="display:none;">',
		               			'<i class="release_icon" style=display:none></i>',
			               		'已发布',
			               		'<i class="share-down-arrow"></i>',
			               		'<i class="share-up-arrow" style="display:none"></i>',	               		
			               		'<span class="speak-share-cancle" style="display:none;">取消发布</span>',
		               		'</a>',
					        '<a class="speak-share" result_id={{value.result_id}}>',
					        	'<i class="release_icon"></i>',
			               		'发布',
		               		'</a>',
					        '{{/if}}',
		               	'</div>',
		               	'<div class="speak-share-cutline"></div>',
		            '{{/each}}',
		       	'{{/if}}',
	        '</div>',
       	'</div>'
    ].join('')
})
