'use strict'

define(function(){
  return [
    // 非会员 有预约
    '<img src="../../i/member_tit.jpg"/>',
  '<div class="member_con">',
  ' <div class="m_txt">',
  '   <div class="middle_tab">',
  '      <span class="font14 bold mtop15">{{data.nickName}}</span>',
  '     <p class="mtop5">今天是<span class="blue509">{{data.today}}</span>，最近一次托福考试是在<span class="blue509">{{data.latest}}</span></p>',
  '   </div>',
  ' </div>',
   '<div class="m_con">',
       '<div class="text-left">',
           '<p class="m_bluebg">今日课程</p>',
           '<div class="pleft10 pr10 text-center">',
         '<p class="text-left">非会员或基础会员没有免费的直播课程，你可以单独购买或者升级会员等级</p>',
           '<button class="light_btn mtop20 " id="goQuestion"><img class="mright5 vm" src="../../i/home_ip.png" /><span class="vm">咨询客服</span></button>',
           '</div>',
           // '{{each data.currentList as value index}}',
           //   '<div class="text-left mleft15 font12 mtop20">',
           //       '<p>{{value.name}}</p>',
           //       '<p class="m_class">',
           //           '<span class="mr10">{{value.startTime}} - {{value.endTime}}</span>',
           //           '<span class="mright20" style="margin-left:12px;">{{value.nameSub}}</span>',
           //           '<button class="light_btn fr_btn" data-coursesUrl="{{value.coursesUrl}}" id="goLive">进入直播</button>',
           //       '</p>',
           //       // '<p class="m_class">',
           //       //     '<span class="mr10 mtop10">17：00 - 18：00</span>',
           //       //     '<span class="mright20 mtop10">听力</span>',
           //       //     // '<button class="light_btn fr_btn" >进入直播</button>',
           //       // '</p>',
           //   '</div>',
           // '{{/each}}',
           // '<div class="text-left mleft15 font12 mtop20">',
           //     '<p>大咖冲刺班</p>',
           //     '<p class="m_class">',
           //         '<span class="mr10">17：00 - 18：00</span>',
           //         // '<button class="light_btn fr_btn" >进入直播</button>',
           //     '</p>',
           // '</div>',
       '</div>',
       // '<div class="text-left">',
       //     '<p class="m_bluebg">下次课程</p>',
       //     // '<p class="mleft15 mtop10 font12 "><span>2015年1月2日</span>，平日基础班，周末强化班。</p>',
       //     '{{each data.nextList as value index}}',
       //       '<div class="text-left mleft15 font12 mtop20">',
       //           '<p>{{value.name}}</p>',
       //           '<p class="m_class">',
       //               '<span class="mr10">{{value.startTime}} - {{value.endTime}}</span>',
       //               '<span class="mright20" style="margin-left:12px;">{{value.nameSub}}</span>',
       //               // '<button class="light_btn fr_btn" data-coursesUrl="{{value.coursesUrl}}" id="goLive">进入直播</button>',
       //           '</p>',
       //       '</div>',
       //     '{{/each}}',
       // '</div>',
       '<div class="text-left">',
           '<p class="m_bluebg">今日练习</p>',
           '<p class="mleft15 mtop15 font12 ">你还没有成为小马会员，暂时没有练习计划。</p>',
           // '<p class="text-center"><button class="deep_btn mtop10" id="goMember">查看会员权益</button></p>',
       '</div>',
   '</div>',
   '</div>'
  ].join('')
})
