'use strict'

define(function(){
  return [
  // 基础会员登录
  '<img src="../../i/member_tit.jpg"/>',
  '<div class="member_con">',
  ' <div class="m_txt">',
  '   <div class="middle_tab">',
  '      <span class="font14 bold mtop15">{{data.nickName}}</span> <span class="grey76 mleft5">基础会员</span>',
  '     <p class="mtop5">今天是<span class="blue509">{{data.today}}</span>，最近一次托福考试是在<span class="blue509">{{data.latest}}</span></p>',
  '   </div>',
  ' </div>',
 '<div class="m_con">',
     '<div>',
         '<p class="m_bluebg text-left">今日课程</p>',
         '<div class="pleft10 pr10 text-center">',
         '<p class="text-left">非会员或基础会员没有免费的直播课程，你可以单独购买或者升级会员等级</p>',
           '<button class="light_btn mtop20 " id="goQuestion"><img class="mright5 vm" src="../../i/home_ip.png" /><span class="vm">咨询客服</span></button>',
           '</div>',
         // '<p class="mleft15 mtop15 font12 text-left">基础会员没有免费的直播课程，你可以单独购买或者升级会员等级。</p>',
         // '<button class="light_btn mtop10" id="goCourse">去课程中看看</button>',
         '</br>', 
         // '<button class="orange_btn mtop10">升级会员权益</button>',
     '</div>',
     '<div>',
         '<p class="m_bluebg text-left">今日练习</p>',
         '<ul class="pratice_num clearfix" style="">',
         '{{each data.questionContent as value index}}',
         '    <li>',
         '        <span  class="font20">{{value.ccount}}</span>',
         '        <p class="font12">{{value.cname}}<span class="home_ok"></span></p>',

         '    </li>',
         '{{/each}}',
         '</ul>',
         // '<p class="blue509 mtop10 text-left mleft15" style="margin-bottom: 20px;">{{data.description}}</p>',
         '{{if data.moduleInfoList.length != 0}}',
           '{{each data.moduleInfoList as value index}}',
             '<p class="m_class text-left mleft15">',
                 '<span class="mr10">{{value.moduleName}}</span>',
                 '{{if value.isShow}}',
                 '<button class="deep_btn fr_btn" data-moduleType="{{value.moduleType}}" id="goExercise">去练习</button>',
                 '{{/if}}',
             '</p>',
           '{{/each}}',
          '{{else}}',
            '<p class="m_class text-left mleft15">',
                 '<span class="mr10">暂无计划</span>',
             '</p>',
         '{{/if}}',
         // '<p class="m_class text-left mleft15">',
         //     '<span class="mr10">阅读词汇 Unit 3-5</span>',
         //     '<button class="deep_btn fr_btn" >去练习</button>',
         // '</p>',
         // '<p class="m_class text-left mleft15">',
         //     '<span class="mr10">阅读词汇 Unit 3-5</span>',
         //     '<button class="deep_btn fr_btn" >去练习</button>',
         // '</p>',
     '</div>',
  ' </div>',
  '</div>'
  ].join('')
})
