'use strict'

define(function(){
  return [
  '<div class="s_jieshao">',
  '  <p><span class="b_vertical"></span><span class="vm">基础练习</span></p>',
  '  <ul class="clear_li">',
  '        <li id="vol">',
  '           <div class="a_homeall"> ',
  '             <div class="s_homeimg s_homeimg1"></div>',
  '             <div class="show"></div>',
  '           </div> ',
  '           <div class="s_homefont"><span class="mleft10">阅读词汇</span><span class="fright mright10">></span></div>',
  '        </li>',
  '        <li id="gram">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg2"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '            <div class="s_homefont"><span class="mleft10">语法</span><span class="fright mright10">></span></div>',
  '        </li>',
  '        <li id="dic">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg3"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '            <div class="s_homefont"><span class="mleft10">听写</span><span class="fright mright10">></span></div>',
  '        </li>',
  '        <li id="listen">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg4"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '            <div class="s_homefont"><span class="mleft10">音译互辩</span><span class="fright mright10">></span></div>',
  '        </li>',
  '        <li id="reWrite">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg5"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '            <div class="s_homefont"><span class="mleft10">记忆复写</span><span class="fright mright10">></span></div>',
  '        </li>',
  '        <li id="tpoWrite">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg6"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '            <div class="s_homefont"><span class="mleft10">综合填空</span><span class="fright mright10">></span></div>',
  '        </li>',
  '        <li style="cursor:auto;">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg7"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '            <div class="s_homefont"><span class="mleft10">复述</span><span class="fright mright10" style="font-size:10px;color:#767676;">请到APP上使用</span></div>',
  '        </li>',
  '        <li style="cursor:auto;">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg8"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '            <div class="s_homefont"><span class="mleft10">跟读</span><span class="fright mright10" style="font-size:10px;color:#767676;">请到APP上使用</span></div>',
  '        </li>',
  '    </ul>',
  '</div>',
  '<div class="s_jieshao mtop20">',
  '    <p><span class="b_vertical"></span><span class="vm">进阶练习</span></p>',
  '    <ul class="clear_li">',
  '       <li id="jinJie1">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg9"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '           <div class="s_homefont"><span class="mleft10">TPO 阅读</span><span class="fright mright10">></span></div>',
  '       </li>',
  '       <li id="jinJie2">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg10"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '           <div class="s_homefont"><span class="mleft10">TPO 听力</span><span class="fright mright10">></span></div>',
  '       </li>',
  '       <li id="jinJie3">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg11"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '           <div class="s_homefont"><span class="mleft10">综合口语</span><span class="fright mright10">></span></div>',
  '       </li>',
  '       <li id="jinJie4">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg12"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '           <div class="s_homefont"><span class="mleft10">综合写作</span><span class="fright mright10">></span></div>',
  '       </li>',
  '       <li id="jinJie5">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg13"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '           <div class="s_homefont"><span class="mleft10">独立口语</span><span class="fright mright10">></span></div>',
  '       </li>',
  '       <li id="jinJie6">',
  '            <div class="a_homeall"> ',
  '              <div class="s_homeimg s_homeimg14"></div>',
  '              <div class="show"></div>',
  '            </div> ',
  '           <div class="s_homefont"><span class="mleft10">独立写作</span><span class="fright mright10">></span></div>',
  '       </li>',
  '    </ul>',
  ' </div>',
  ' <div class="s_jieshao mtop20">',
  '     <p><span class="b_vertical"></span><span class="vm">冲刺练习</span></p>',
  '     <ul class="clear_li">',
  '         <li id="chongCi4">',
  '             <div class="a_homeall"> ',
  '               <div class="s_homeimg s_homeimg15"></div>',
  '               <div class="show"></div>',
  '             </div> ',
  '             <div class="s_homefont"><span class="mleft10">写作批改</span><span class="fright mright10">></span></div>',
  '         </li>',
  '         <li id="chongCi3">',
  '             <div class="a_homeall"> ',
  '               <div class="s_homeimg s_homeimg16"></div>',
  '               <div class="show"></div>',
  '             </div> ',
  '             <div class="s_homefont"><span class="mleft10">口语批改</span><span class="fright mright10">></span></div>',
  '         </li>',
  '         <li id="chongCi1">',
  '             <div class="a_homeall"> ',
  '               <div class="s_homeimg s_homeimg17"></div>',
  '               <div class="show"></div>',
  '             </div> ',
  '             <div class="s_homefont"><span class="mleft10">TPO 阅读刷题</span><span class="fright mright10">></span></div>',
  '         </li>',
  '         <li id="chongCi2">',
  '             <div class="a_homeall"> ',
  '               <div class="s_homeimg s_homeimg18"></div>',
  '               <div class="show"></div>',
  '             </div> ',
  '             <div class="s_homefont"><span class="mleft10">TPO 听力刷题</span><span class="fright mright10">></span></div>',
  '         </li>',
  '     </ul>',
  '  </div>'
  ].join('')
})
