'use strict'

define(function(){
  return [
  // 会员练完后未过期
  '<img src="../../i/member_tit.jpg"/>',
  '<div class="member_con">',
  ' <div class="m_txt">',
  '   <div class="middle_tab">',
  '      <span class="font14 bold mtop15">劉小妖</span> <span class="grey76 mleft5">铁杆会员</span>',
  '     <p class="mtop5">今天是<span class="blue509">12月07日</span>，最近一次托福考试是在<span class="blue509">12月26日</span></p>',
  '   </div>',
  ' </div>',
  '<div class="m_con">',
      '<div class="text-left">',
          '<p class="m_bluebg">今日课程</p>',
          '<div class="text-left mleft15 font12">',
              '<p>平日基础班</p>',
              '<p class="m_class">',
                  '<span class="mr10">17：00 - 18：00</span>',
                  '<span class="mright20">听力</span>',
                  // '<button class="light_btn fr_btn" >进入直播</button>',
              '</p>',
              '<p class="m_class">',
                  '<span class="mr10 mtop10">17：00 - 18：00</span>',
                  '<span class="mright20 mtop10">听力</span>',
                  // '<button class="light_btn fr_btn" >进入直播</button>',
              '</p>',
          '</div>',
          '<div class="text-left mleft15 font12 mtop20">',
              '<p>大咖冲刺班</p>',
              '<p class="m_class">',
                  '<span class="mr10">17：00 - 18：00</span>',
                  // '<button class="light_btn fr_btn" >进入直播</button>',
              '</p>',
          '</div>',
      '</div>',
      '<div class="text-left">',
          '<p class="m_bluebg">下次课程</p>',
          '<p class="mleft15 mtop10 font12 "><span>2015年1月2日</span>，平日基础班，周末强化班。</p>',
      '</div>',
      '<div class="text-left">',
          '<p class="m_bluebg">今日练习</p>',
          '<p class="mleft15 mtop15 font12 ">恭喜，你已经完成了整个会员练习计划</p>',
          '<p class="text-center"><button class="deep_btn mtop10">再来一遍</button></p>',
      '</div>',
  '</div>',
  '</div>'
  ].join('')
})
