'use strict'

define(function(){
  return [
  '<img src="../../i/member_tit.jpg"/>',
  '<div class="member_con">',
  ' <div class="m_txt">',
  '   <div class="middle_tab">',
  '      <span class="font14 bold mtop15">{{data.nickName}}</span> <span class="grey76 mleft5">{{data.vipName}}</span>',
  '     <p class="mtop5">今天是<span class="blue509">{{data.today}}</span>，最近一次托福考试是在<span class="blue509">{{data.latest}}</span></p>',
  '   </div>',
  ' </div>',
  '<div class="m_con">',
  '     <div class="text-left">',
  '         <p class="m_bluebg">今日课程</p>',
            '{{each data.currentList as value index}}',
             '<div class="text-left mleft15 font12 mtop20">',
                 '<p>{{value.name}}</p>',
                 '<p class="m_class">',
                     '<span class="mr10">{{value.startTime}} - {{value.endTime}}</span>',
                     '<span class="mright20" style="margin-left:12px;">{{value.nameSub}}</span>',
                     '<button class="light_btn fr_btn" data-coursesUrl="{{value.coursesUrl}}" id="goLive">进入直播</button>',
                 '</p>',
             '</div>',
           '{{/each}}',
  '     </div>',
  '<div class="text-left">',
           '<p class="m_bluebg">下次课程</p>',
           // '<p class="mleft15 mtop10 font12 "><span>2015年1月2日</span>，平日基础班，周末强化班。</p>',
           '{{each data.nextList as value index}}',
             '<div class="text-left mleft15 font12 mtop20">',
                 '<p>{{value.name}}</p>',
                 '<p class="m_class">',
                     '<span class="mr10">{{value.startTime}} - {{value.endTime}}</span>',
                     '<span class="mright20" style="margin-left:12px;">{{value.nameSub}}</span>',
                     // '<button class="light_btn fr_btn" data-coursesUrl="{{value.coursesUrl}}" id="goLive">进入直播</button>',
                 '</p>',
             '</div>',
           '{{/each}}',
       '</div>',
      '<div>',
         '<p class="m_bluebg text-left">今日练习</p>',
         '<ul class="pratice_num clearfix" style="">',
         '{{each data.questionContent as value index}}',
         '    <li>',
         '        <span  class="font20">{{value.ccount}}</span>',
         '        <p class="font12">{{value.cname}}<span class="home_ok"></span></p>',

         '    </li>',
         '{{/each}}',
         '</ul>',
         // '<p class="blue509 mtop10 text-left mleft15" style="margin-bottom: 20px;">{{data.description}}</p>',
         '{{if data.moduleInfoList.length != 0}}',
           '{{each data.moduleInfoList as value index}}',
             '<p class="m_class text-left mleft15">',
                 '<span class="mr10">{{value.moduleName}}</span>',
                 '{{if value.isShow}}',
                 '<button class="deep_btn fr_btn" data-moduleType="{{value.moduleType}}" id="goExercise">去练习</button>',
                 '{{/if}}',
             '</p>',
           '{{/each}}',
         '{{else}}',
            '<p class="m_class text-left mleft15">',
                 '<span class="mr10">暂无计划</span>',
             '</p>',
         '{{/if}}',
     '</div>',
  // '<div class="text-left">',
  //         '<p class="m_bluebg">今日练习</p>',
  //         '<p class="mleft15 mtop15 font12 ">恭喜，你已经完成了整个会员练习计划</p>',
  //         '<p class="text-center"><button class="deep_btn mtop10">再来一遍</button></p>',
  //     '</div>',
  '  </div>',
  ' </div>'
  ].join('')
})
